### ISSUE TITLE
Community-color-schemes doesn't load in settings

### ISSUE THREAD

**Issue by SolarAquarion** [Eugeny/terminus#182]
I press "colorschemes" under terminal and nothing loads

**Comment by Eugeny** [comment]
Please click `Dev tools` on the main Settings page and see if any errors pop up on the Console tab when you click the Color Schemes.

**Comment by SolarAquarion** [comment]
@Eugeny for some reason after i upgraded to alpha 28 terminus is staying by the "loading" screen

**Comment by SolarAquarion** [comment]
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("            <ng-template #scrollablePlaceholder></ng-template>
        </perfect-scrollbar>
        [WARNING ->]<template #nonScrollablePlaceholder [ngIf]="!scrollable"></template>
    "): ng:///AppModule/TabBodyComponent.html@4:8

One thing i get is that @Eugeny also this
errors.ts:42 ERROR Error: Uncaught (in promise): Error: Cannot find module '/home/solaraquarion/.hyper_plugins/node_modules/.bin'
Error: Cannot find module '/home/solaraquarion/.hyper_plugins/node_modules/.bin'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/opt/Terminus/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at Module.nodeRequire.require (file:///opt/Terminus/resources/app.asar/dist/bundle.js:2758:28)
    at require (internal/module.js:20:19)
    at plugins.forEach.plugin (/opt/Terminus/resources/builtin-plugins/terminus-terminal/dist/index.js:21452:37)
    at Array.forEach (native)
    at HyperColorSchemes.<anonymous> (/opt/Terminus/resources/builtin-plugins/terminus-terminal/dist/index.js:21451:21)
    at Generator.next (<anonymous>)
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/opt/Terminus/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at Module.nodeRequire.require (file:///opt/Terminus/resources/app.asar/dist/bundle.js:2758:28)
    at require (internal/module.js:20:19)
    at plugins.forEach.plugin (/opt/Terminus/resources/builtin-plugins/terminus-terminal/dist/index.js:21452:37)
    at Array.forEach (native)
    at HyperColorSchemes.<anonymous> (/opt/Terminus/resources/builtin-plugins/terminus-terminal/dist/index.js:21451:21)
    at Generator.next (<anonymous>)
    at resolvePromise (/opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:770:31)
    at /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:696:17
    at rejected (/opt/Terminus/resources/builtin-plugins/terminus-terminal/dist/index.js:1054:89)
    at ZoneDelegate.invoke (/opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:391:26)
    at Object.onInvoke (/opt/Terminus/resources/app.asar/node_modules/@angular/core/bundles/core.umd.js:3922:33)
    at ZoneDelegate.invoke (/opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:390:32)
    at Zone.run (/opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:141:43)
    at /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:818:57
    at ZoneDelegate.invokeTask (/opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:424:31)
    at Object.onInvokeTask (/opt/Terminus/resources/app.asar/node_modules/@angular/core/bundles/core.umd.js:3913:33)

This

**Comment by SolarAquarion** [comment]
@Eugeny I'm getting that

**Comment by comp** [comment]
`Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("            <ng-template #scrollablePlaceholder></ng-template>
        </perfect-scrollbar>
        [WARNING ->]<template #nonScrollablePlaceholder [ngIf]="!scrollable"></template>
    "): ng:///AppModule/TabBodyComponent.html@4:8


ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'blue' of undefined
TypeError: Cannot read property 'blue' of undefined
    at Object.exports.decorateConfig.config [as decorateConfig] (C:\Users\GTC-IT\.hyper_plugins\node_modules\hyper-material-box\index.js:62:35)
    at plugins.forEach.plugin (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\builtin-plugins\terminus-terminal\dist\index.js:21454:41)
    at Array.forEach (native)
    at HyperColorSchemes.<anonymous> (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\builtin-plugins\terminus-terminal\dist\index.js:21451:21)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\builtin-plugins\terminus-terminal\dist\index.js:21432:58)
    at ZoneDelegate.invoke (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\app.asar\node_modules\zone.js\dist\zone.js:391:26)
    at Object.onInvoke (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:3922:33)
    at ZoneDelegate.invoke (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\app.asar\node_modules\zone.js\dist\zone.js:390:32)
    at Zone.run (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\app.asar\node_modules\zone.js\dist\zone.js:141:43)
    at Object.exports.decorateConfig.config [as decorateConfig] (C:\Users\GTC-IT\.hyper_plugins\node_modules\hyper-material-box\index.js:62:35)
    at plugins.forEach.plugin (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\builtin-plugins\terminus-terminal\dist\index.js:21454:41)
    at Array.forEach (native)
    at HyperColorSchemes.<anonymous> (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\builtin-plugins\terminus-terminal\dist\index.js:21451:21)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\builtin-plugins\terminus-terminal\dist\index.js:21432:58)
    at ZoneDelegate.invoke (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\app.asar\node_modules\zone.js\dist\zone.js:391:26)
    at Object.onInvoke (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:3922:33)
    at ZoneDelegate.invoke (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\app.asar\node_modules\zone.js\dist\zone.js:390:32)
    at Zone.run (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\app.asar\node_modules\zone.js\dist\zone.js:141:43)
    at resolvePromise (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\app.asar\node_modules\zone.js\dist\zone.js:770:31)
    at C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\app.asar\node_modules\zone.js\dist\zone.js:696:17
    at rejected (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\builtin-plugins\terminus-terminal\dist\index.js:1054:89)
    at ZoneDelegate.invoke (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\app.asar\node_modules\zone.js\dist\zone.js:391:26)
    at Object.onInvoke (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:3922:33)
    at ZoneDelegate.invoke (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\app.asar\node_modules\zone.js\dist\zone.js:390:32)
    at Zone.run (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\app.asar\node_modules\zone.js\dist\zone.js:141:43)
    at C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\app.asar\node_modules\zone.js\dist\zone.js:818:57
    at ZoneDelegate.invokeTask (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\app.asar\node_modules\zone.js\dist\zone.js:424:31)
    at Object.onInvokeTask (C:\Users\GTC-IT\AppData\Local\terminus\app-1.0.0-alpha28\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:3913:33)`

**Comment by equinox** [comment]
@SolarAquarion If you look in /home/solaraquarion/.hyper_plugins/node_modules/.bin and if it's empty, try deleting it. Fixed this for me (my Shell setting also wasn't working as well as the colour scheme).

**Comment by Eugeny** [comment]
Fixed
