### ISSUE TITLE
The Terminus can't load a shell (add "useConPTY: false" to my config file is useless)

### ISSUE THREAD

**Issue by LinkZyy** [Eugeny/terminus#1941]
![批注 2019-12-31 005937](https://user-images.githubusercontent.com/42362118/71591857-d8ac8700-2b68-11ea-968b-bc4a8cbb8ca0.png)

I've tried the solution : add "useConPTY: false" to my config file, but it didn't work.what should i do?

information:
﻿
C:\Users\ZYY\AppData…s\core.umd.js:15768 ERROR Error: File not found: 
    at new WindowsPtyAgent (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:77:36)
    at new WindowsTerminal (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:49:24)
    at spawn (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\node-pty\lib\index.js:28:12)
    at Object.mod.spawn (webpack-internal:///2058:9:20)
    at Session.start (webpack-internal:///6:460:39)
    at SessionsService.addSession (webpack-internal:///6:662:17)
    at TerminalTabComponent.initializeSession (webpack-internal:///6:2380:23)
    at SafeSubscriber.eval [as _next] (webpack-internal:///6:2375:18)
    at SafeSubscriber.__tryOrUnsub (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:143:22)
    at Subscriber._next (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\operators\throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at TakeSubscriber._next (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\operators\take.js:54:30)
    at TakeSubscriber.Subscriber.next (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Subject.next (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subject.js:60:25)
    at TerminalTabComponent.eval (webpack-internal:///6:2062:32)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///6:68:71)
    at new ZoneAwarePromise (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:910:29)
    at __awaiter (webpack-internal:///6:64:12)
    at SafeSubscriber.eval [as _next] (webpack-internal:///6:2060:93)
    at SafeSubscriber.__tryOrUnsub (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:143:22)
    at Subscriber._next (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\operators\throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at TakeSubscriber._next (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\operators\take.js:54:30)
    at TakeSubscriber.Subscriber.next (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at ReplaySubject.Subject.next (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subject.js:60:25)
    at ReplaySubject.nextInfiniteTimeWindow (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\ReplaySubject.js:48:31)
    at eval (webpack-internal:///6:1654:25)
    at e.fire (webpack-internal:///2320:1:2085)
    at t.resize (webpack-internal:///2320:1:85073)
    at e.resize (webpack-internal:///2320:1:53731)
    at XTermFrontend.resizeHandler (webpack-internal:///6:1702:32)
    at XTermFrontend.attach (webpack-internal:///6:1726:14)
    at Immediate.eval (webpack-internal:///6:2070:31)
    at ZoneDelegate.invokeTask (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423:31)
    at Object.onInvokeTask (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334:37)
    at ZoneDelegate.invokeTask (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:422:60)
    at Zone.runTask (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:195:47)
    at ZoneTask.invokeTask (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:498:34)
    at Immediate.ZoneTask.invoke (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:487:48)
    at Immediate.timer (C:\Users\ZYY\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:2281:29)
    at processImmediate (internal/timers.js:439:21)

Version: 1.0.98
Platform: win32 10.0.18362
Plugins: save-output

**Comment by GamerClassN7** [comment]
HI,
I have same problem after update any news available ???

I love this Terminal but it is basically useless now :(

**Comment by Eugeny** [comment]
Have you tried the 1.0.100 update?

**Comment by LinkZyy** [comment]
> Have you tried the 1.0.100 update?
Thanks for your reply.
I just updated it.But the problem is still existing.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by LinkZyy** [comment]
> Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[Eugeny/terminus](https://github.com/Eugeny/terminus)**A terminal for a more modern age. Contribute to Eugeny/terminus development by creating an account on GitHub.

I'm so sorry for the delay,
I tried it, The result is attached on below,it seems like I lost some files?
I tried re-download the Terminus, but it didn't work.
Thank you very much.
![1](https://user-images.githubusercontent.com/42362118/74137839-7fd21300-4c2b-11ea-94f2-51bd7ecc2848.png)
![2](https://user-images.githubusercontent.com/42362118/74137844-819bd680-4c2b-11ea-97a4-d555b3519dbd.png)
