### ISSUE TITLE
Couldn't open shell

### ISSUE THREAD

**Issue by fuakata** [Eugeny/terminus#2083]
Version: 1.0.101
Platform: win32 10.0.17134
Plugins: none

After upgrading from previous version under Windows 10, Terminus won't let me open any type of shell.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by fuakata** [comment]
C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768 ERROR Error: Uncaught (in promise): Error: Cannot find module './undefined'
Error: Cannot find module './undefined'
    at webpackContextResolve (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-terminal\dist\index.js:2963:11)
    at webpackContext (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-terminal\dist\index.js:2958:11)
    at WSLShellProvider.eval (webpack-internal:///9285:4369:60)
    at Generator.next (<anonymous>)
    at fulfilled (webpack-internal:///9285:65:58)
    at ZoneDelegate.invoke (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:391:26)
    at Object.onInvoke (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17343:37)
    at ZoneDelegate.invoke (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:390:52)
    at Zone.run (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:150:43)
    at C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:889:34
    at ZoneDelegate.invokeTask (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423:31)
    at Object.onInvokeTask (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334:37)
    at ZoneDelegate.invokeTask (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:422:60)
    at Zone.runTask (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:195:47)
    at drainMicroTaskQueue (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:601:35)
    at resolvePromise (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:831:31)
    at C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:741:17
    at rejected (webpack-internal:///9285:66:89)
    at ZoneDelegate.invoke (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:391:26)
    at Object.onInvoke (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17343:37)
    at ZoneDelegate.invoke (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:390:52)
    at Zone.run (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:150:43)
    at C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:889:34
    at ZoneDelegate.invokeTask (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423:31)
    at Object.onInvokeTask (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334:37)
    at ZoneDelegate.invokeTask (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:422:60)
    at Zone.runTask (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:195:47)
    at drainMicroTaskQueue (C:\Users\garcej1\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:601:35)
