### ISSUE TITLE
Fail at install-deps: FontManager

### ISSUE THREAD

**Issue by ClementParis016** [Eugeny/terminus#221]
I wanted to run a local copy of Terminus to start working on an issue but I'm running into issues at install.

Following the steps at `HACKING.md`, it's failing at  `./scripts/install-deps.js` due to some error related to FontManager.

Here is the console output, which seems to come from a `node-gyp` execution and gets down to a deep V8 stack trace:
```console
error /mnt/d/projects/terminus/terminus-terminal/node_modules/font-manager: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /mnt/d/projects/terminus/terminus-terminal/node_modules/font-manager
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.4.0 | linux | x64
gyp info spawn /usr/bin/python2.7
gyp info spawn args [ '/home/cparis/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/d/projects/terminus/terminus-terminal/node_modules/font-manager/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/cparis/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/cparis/.node-gyp/8.4.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/cparis/.node-gyp/8.4.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/cparis/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/cparis/.node-gyp/8.4.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/mnt/d/projects/terminus/terminus-terminal/node_modules/font-manager',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/mnt/d/projects/terminus/terminus-terminal/node_modules/font-manager/build'
  CXX(target) Release/obj.target/fontmanager/src/FontManager.o
In file included from ../node_modules/nan/nan.h:194:0,
                 from ../src/FontManager.cc:5:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::MaybeLocal<v8::Object> Nan::CloneElementAt(v8::Local<v8::Array>, uint32_t)’:
../node_modules/nan/nan_maybe_43_inl.h:220:58: warning: ‘v8::MaybeLocal<v8::Object> v8::Array::CloneElementAt(v8::Local<v8::Context>, uint32_t)’ is deprecat
ed: Cloning is not supported. [-Wdeprecated-declarations]
   return array->CloneElementAt(GetCurrentContext(), index);
                                                          ^
In file included from /home/cparis/.node-gyp/8.4.0/include/node/v8.h:26:0,
                 from /home/cparis/.node-gyp/8.4.0/include/node/node.h:63,
                 from ../src/FontManager.cc:2:
/home/cparis/.node-gyp/8.4.0/include/node/v8.h:3458:36: note: declared here
                 MaybeLocal<Object> CloneElementAt(Local<Context> context,
                                    ^
/home/cparis/.node-gyp/8.4.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../node_modules/nan/nan_new.h:189:0,
                 from ../node_modules/nan/nan.h:200,
                 from ../src/FontManager.cc:5:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::
BooleanObject>::New(bool)’:
../node_modules/nan/nan_implementation_12_inl.h:40:38: warning: ‘static v8::Local<v8::Value> v8::BooleanObject::New(bool)’ is deprecated: Pass an isolate [-
Wdeprecated-declarations]
   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                      ^
In file included from /home/cparis/.node-gyp/8.4.0/include/node/v8.h:26:0,
                 from /home/cparis/.node-gyp/8.4.0/include/node/node.h:63,
                 from ../src/FontManager.cc:2:
/home/cparis/.node-gyp/8.4.0/include/node/v8.h:4749:56: note: declared here
   V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                        ^
/home/cparis/.node-gyp/8.4.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../src/FontManager.cc:5:0:
../node_modules/nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Lo
cal<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’:
../node_modules/nan/nan.h:1961:16: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallbac
k, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     , attribute);
                ^
In file included from /home/cparis/.node-gyp/8.4.0/include/node/v8.h:26:0,
                 from /home/cparis/.node-gyp/8.4.0/include/node/node.h:63,
                 from ../src/FontManager.cc:2:
/home/cparis/.node-gyp/8.4.0/include/node/v8.h:3128:22: note: declared here
                 bool SetAccessor(Local<Name> name,
                      ^
/home/cparis/.node-gyp/8.4.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
  CXX(target) Release/obj.target/fontmanager/src/FontManagerLinux.o
../src/FontManagerLinux.cc:1:35: fatal error: fontconfig/fontconfig.h: No such file or directory
compilation terminated.
fontmanager.target.mk:96: recipe for target 'Release/obj.target/fontmanager/src/FontManagerLinux.o' failed
make: *** [Release/obj.target/fontmanager/src/FontManagerLinux.o] Error 1
make: Leaving directory '/mnt/d/projects/terminus/terminus-terminal/node_modules/font-manager/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/cparis/.config/yarn/global/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-43-Microsoft
gyp ERR! command "/home/cparis/.nvm/versions/node/v8.4.0/bin/node" "/home/cparis/.yarn/bin/node-gyp" "rebuild"
gyp ERR! cwd /mnt/d/projects/terminus/terminus-terminal/node_modules/font-manager
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

Using Yarn v1.0.1, node-gyp v3.6.2 and Node v8.4.0.

I'm working under WSL (Bash on Ubuntu on Windows), though I'm not sure if it has something to do with the problem.

So, do you have any idea about how to fix this? Or maybe it's not important and I could just comment out some code and bypass this error?

**Comment by Eugeny** [comment]
Try installing `libfontconfig1-dev` (`apt install libfontconfig1-dev`)

**Comment by ClementParis016** [comment]
@Eugeny Thanks, installing `libfontconfig1-dev` solved the issue! But unfortunately I'm still running into issues and solving them one after the other is slow and painful, so I guess I will just stop trying to run it under WSL. Will try on Windows or Ubuntu, what do you use on your side?

**Comment by Eugeny** [comment]
To answer your question, I've successfully set up the environment on Windows, macOS and Linux.
