### ISSUE TITLE
Theme Development: Font Manager Failure 

### ISSUE THREAD

**Issue by cliffordfajardo** [Eugeny/terminus#2257]
**Current Machine Details**:
- Platform MacOS Catalina 
- Node version: 
      - **v13.6.0  (failed)**
      - v8.13.0 (works)
      - v10.0.0 (works)
      - v11.1.0 (works, but install took 5x as long as previous versions & with lots of deprecation warnings)

**Steps to Reproduce Error**:
1. I attempted to create a theme, so I forked the [altair terminus theme](https://github.com/yxuko/terminus-altair/)
2. After running `npm i` I got the following node-gyp error:

**Stack Trace for Error on Node 13.6.0**
<details>

```
terminus-altair => master $ npm i

> font-manager@0.3.0 install /Users/cliffordfajardo/Desktop/terminus-altair/node_modules/font-manager
> node-gyp rebuild

  CXX(target) Release/obj.target/fontmanager/src/FontManager.o
In file included from ../src/FontManager.cc:5:
In file included from ../../nan/nan.h:221:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1: error: no viable conversion from 'Local<v8::Context>' to 'v8::Isolate *'
X(Boolean)
^~~~~~~~~~
../../nan/nan_converters_43_inl.h:18:23: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:2762:37: note: passing argument to parameter 'isolate' here
  Local<Boolean> ToBoolean(Isolate* isolate) const;
                                    ^
In file included from ../src/FontManager.cc:5:
In file included from ../../nan/nan.h:221:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:40:1: error: no viable conversion from 'Local<v8::Context>' to 'v8::Isolate *'
X(bool, Boolean)
^~~~~~~~~~~~~~~~
../../nan/nan_converters_43_inl.h:37:29: note: expanded from macro 'X'
  return val->NAME ## Value(isolate->GetCurrentContext());                     \
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:2771:30: note: passing argument to parameter 'isolate' here
  bool BooleanValue(Isolate* isolate) const;
                             ^
In file included from ../src/FontManager.cc:5:
In file included from ../../nan/nan.h:222:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:103:42: error: no viable conversion from 'v8::Isolate *' to 'Local<v8::Context>'
  return scope.Escape(v8::Function::New( isolate
                                         ^~~~~~~
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:189:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'v8::Isolate *' to 'const v8::Local<v8::Context> &' for 1st argument
class Local {
      ^
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:189:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
      'v8::Isolate *' to 'v8::Local<v8::Context> &&' for 1st argument
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:193:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'v8::Isolate *'
  V8_INLINE Local(Local<S> that)
            ^
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:4313:22: note: passing argument to parameter 'context' here
      Local<Context> context, FunctionCallback callback,
                     ^
In file included from ../src/FontManager.cc:5:
In file included from ../../nan/nan.h:222:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337:37: error: too few arguments to function call, expected 2, have 1
  return v8::StringObject::New(value).As<v8::StringObject>();
         ~~~~~~~~~~~~~~~~~~~~~      ^
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:5688:3: note: 'New' declared here
  static Local<Value> New(Isolate* isolate, Local<String> value);
  ^
In file included from ../src/FontManager.cc:5:
In file included from ../../nan/nan.h:222:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337:58: error: expected '(' for function-style cast or type construction
  return v8::StringObject::New(value).As<v8::StringObject>();
                                         ~~~~~~~~~~~~~~~~^
../../nan/nan_implementation_12_inl.h:337:60: error: expected expression
  return v8::StringObject::New(value).As<v8::StringObject>();
                                                           ^
In file included from ../src/FontManager.cc:5:
../../nan/nan.h:1063:53: error: too few arguments to function call, single argument 'context' was not specified
      v8::Local<v8::String> string = from->ToString();
                                     ~~~~~~~~~~~~~~ ^
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:2750:3: note: 'ToString' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
  ^
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/FontManager.cc:5:
../../nan/nan.h:1073:37: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'char *'
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                    ^~~~
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:2947:26: note: passing argument to parameter 'isolate' here
  int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
                         ^
In file included from ../src/FontManager.cc:5:
../../nan/nan.h:1847:28: error: no matching member function for call to 'Set'
    New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
    ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../src/FontManager.cc:5:
../../nan/nan.h:1853:28: error: no matching member function for call to 'Set'
    New(persistentHandle)->Set(key, value);
    ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../src/FontManager.cc:5:
../../nan/nan.h:1859:28: error: no matching member function for call to 'Set'
    New(persistentHandle)->Set(index, value);
    ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../src/FontManager.cc:5:
../../nan/nan.h:1865:32: error: no matching member function for call to 'Get'
        New(persistentHandle)->Get(New(key).ToLocalChecked()));
        ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/FontManager.cc:5:
../../nan/nan.h:1871:48: error: no matching member function for call to 'Get'
    return scope.Escape(New(persistentHandle)->Get(key));
                        ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/FontManager.cc:5:
../../nan/nan.h:1876:48: error: no matching member function for call to 'Get'
    return scope.Escape(New(persistentHandle)->Get(index));
                        ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/FontManager.cc:5:
In file included from ../../nan/nan.h:2690:
../../nan/nan_object_wrap.h:24:25: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(persistent().IsNearDeath());
           ~~~~~~~~~~~~ ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../src/FontManager.cc:5:
In file included from ../../nan/nan.h:2690:
../../nan/nan_object_wrap.h:67:18: error: no member named 'MarkIndependent' in 'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    persistent().MarkIndependent();
    ~~~~~~~~~~~~ ^
../../nan/nan_object_wrap.h:124:26: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(wrap->handle_.IsNearDeath());
           ~~~~~~~~~~~~~ ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../src/FontManager.cc:6:
../src/FontDescriptor.h:115:10: error: no matching member function for call to 'Set'
    res->Set(Nan::New<String>("path").ToLocalChecked(), Nan::New<String>(path).ToLocalChecked());
    ~~~~~^~~
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../src/FontManager.cc:6:
../src/FontDescriptor.h:116:10: error: no matching member function for call to 'Set'
    res->Set(Nan::New<String>("postscriptName").ToLocalChecked(), Nan::New<String>(postscriptName).ToLocalChecked());
    ~~~~~^~~
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/cliffordfajardo/Library/Caches/node-gyp/13.6.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/fontmanager/src/FontManager.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/cliffordfajardo/.my-npm-globals/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/Cellar/node/13.6.0/bin/node" "/Users/cliffordfajardo/.my-npm-globals/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/cliffordfajardo/Desktop/terminus-altair/node_modules/font-manager
gyp ERR! node -v v13.6.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok 
npm WARN @angular/core@7.2.7 requires a peer of zone.js@~0.8.26 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN css-loader@2.1.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-toastr@8.10.2 requires a peer of @angular/core@^5.2.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-toastr@8.10.2 requires a peer of @angular/common@^5.2.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-toastr@8.10.2 requires a peer of @angular/platform-browser@^5.2.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@7.1.0 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN terminus-core@1.0.0-alpha.61-32-g3945873 requires a peer of @angular/animations@4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN terminus-core@1.0.0-alpha.61-32-g3945873 requires a peer of @angular/common@4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN terminus-core@1.0.0-alpha.61-32-g3945873 requires a peer of @angular/core@4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN terminus-core@1.0.0-alpha.61-32-g3945873 requires a peer of @angular/forms@4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN terminus-core@1.0.0-alpha.61-32-g3945873 requires a peer of @angular/platform-browser@4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN terminus-core@1.0.0-alpha.61-32-g3945873 requires a peer of @angular/platform-browser-dynamic@4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN terminus-core@1.0.0-alpha.61-32-g3945873 requires a peer of rxjs@5.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN terminus-core@1.0.0-alpha.61-32-g3945873 requires a peer of zone.js@0.8.4 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! font-manager@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the font-manager@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cliffordfajardo/.npm/_logs/2020-03-15T05_58_26_327Z-debug.log
```

</details>

**Comment by Eugeny** [comment]
`altair` is a third party theme, but I went ahead and updated deps in my own fork - please try basing your theme on it: https://github.com/Eugeny/terminus-altair

I've also send a PR to `terminus-altair`'s author.
