### ISSUE TITLE
There is no Profile

### ISSUE THREAD

**Issue by koumaza** [Eugeny/terminus#2405]
Version: 1.0.106 (Release and CI artifact)
Platform: win32 10.0.19603
Plugins: none

#### Setting >> Shell
![image](https://user-images.githubusercontent.com/44153315/79295493-c6860700-7f13-11ea-8940-bf9db68968f8.png)
Also, New profile does not work.
There is no Profile that is the base.

#### Tried

- Uninstall
- Delete Config (Appdata)

Are there any other steps I should try?

<details>
<summary>Config</summary>
<pre>
<code>
terminal:
  font: Consolas
  shell: clink
  profile: cmd-clink
  rightClick: menu
  pasteOnMiddleClick: true
  copyOnSelect: false
  frontend: xterm
  autoOpen: false
  fontSize: 14
  fallbackFont: null
  linePadding: 0
  bell: 'off'
  bracketedPaste: false
  background: theme
  ligatures: false
  cursor: block
  cursorBlink: true
  customShell: ''
  scrollOnInput: true
  workingDirectory: ''
  alwaysUseWorkingDirectory: false
  altIsMeta: false
  wordSeparator: ' ()[]{}''"'
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: 'rgba(38, 50, 56, 1)'
    selection: null
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  customColorSchemes: []
  environment: {}
  profiles: []
  useConPTY: true
  recoverTabs: true
  warnOnMultilinePaste: true
hotkeys:
  ctrl-c:
    - Ctrl-C
  copy:
    - Ctrl-Shift-C
  paste:
    - Ctrl-Shift-V
  clear: []
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  new-tab:
    - Ctrl-Shift-T
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-next-word:
    - Ctrl-Delete
  search:
    - Ctrl-Shift-F
  shell: {}
  profile: {}
  serial:
    - Alt-K
  settings:
    - 'Ctrl-,'
  ssh:
    - Alt-S
  new-window:
    - Ctrl-Shift-N
  toggle-window:
    - Ctrl+Space
  toggle-fullscreen:
    - F11
    - Alt-Enter
  close-tab:
    - Ctrl-Shift-W
  reopen-tab:
    - Ctrl-Shift-T
  toggle-last-tab: []
  rename-tab:
    - Ctrl-Shift-R
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
  move-tab-left:
    - Ctrl-Shift-PageUp
  move-tab-right:
    - Ctrl-Shift-PageDown
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  split-right:
    - Ctrl-Shift-E
  split-bottom:
    - Ctrl-Shift-D
  split-left: []
  split-top: []
  pane-nav-right:
    - Ctrl-Alt-Right
  pane-nav-down:
    - Ctrl-Alt-Down
  pane-nav-up:
    - Ctrl-Alt-Up
  pane-nav-left:
    - Ctrl-Alt-Left
  pane-maximize:
    - Ctrl-Alt-Enter
  close-pane: []
serial:
  connections: []
  options: {}
ssh:
  connections: []
  recentConnections: []
  options: {}
pluginBlacklist: []
appearance:
  dock: 'off'
  dockScreen: current
  dockFill: 0.5
  tabsLocation: top
  cycleTabs: true
  theme: Standard
  frame: thin
  css: '/* * { color: blue !important; } */'
  opacity: 1
  vibrancy: true
  vibrancyType: blur
enableAnalytics: false
enableWelcomeTab: false
electronFlags:
  - - force_discrete_gpu
    - '0'
enableAutomaticUpdates: true
</code>
</pre>
</details>

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by koumaza** [comment]
This ERROR occurred on Nightly and Alpha.

<details><summary>Error</summary><pre>
<div>
C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4229 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
    at WSLShellProvider.eval (webpack-internal:///5760:4760:47)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///5760:87:71)
    at new ZoneAwarePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:913:33)
    at __awaiter (webpack-internal:///5760:83:12)
    at WSLShellProvider.provide (webpack-internal:///5760:4707:16)
    at eval (webpack-internal:///5760:2778:110)
    at Array.map (<anonymous>)
    at TerminalService.eval (webpack-internal:///5760:2778:99)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///5760:87:71)
    at new ZoneAwarePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:913:33)
    at __awaiter (webpack-internal:///5760:83:12)
    at TerminalService.getShells (webpack-internal:///5760:2777:16)
    at TerminalService.eval (webpack-internal:///5760:2785:39)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///5760:87:71)
    at new ZoneAwarePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:913:33)
    at __awaiter (webpack-internal:///5760:83:12)
    at TerminalService.reloadShells (webpack-internal:///5760:2783:16)
    at new TerminalService (webpack-internal:///5760:2697:14)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11231:41
    at _callFactory (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:21946:24)
    at _createProviderInstance (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:21904:30)
    at resolveNgModuleDep (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:21878:21)
    at _callFactory (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:21948:32)
    at _createProviderInstance (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:21904:30)
    at resolveNgModuleDep (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:21864:25)
    at NgModuleRef_.get (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22456:20)
    at injectInjectorOnly (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1006:37)
    at ɵɵinject (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1011:61)
    at injectArgs (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1103:27)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11231:87
    at _callFactory (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:21946:24)
    at _createProviderInstance (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:21904:30)
    at resolveNgModuleDep (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:21878:21)
    at _createClass (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:21937:36)
    at _createProviderInstance (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:21901:30)
    at initNgModule (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:21833:36)
    at new NgModuleRef_ (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22444:13)
    at Object.createNgModuleRef (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22433:16)
    at NgModuleFactory_.create (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:32348:29)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:28514:47
    at ZoneDelegate.invoke (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:386:30)
    at Object.onInvoke (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:27984:37)
    at ZoneDelegate.invoke (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:385:36)
    at Zone.run (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:143:47)
    at NgZone.run (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:27881:32)
    at PlatformRef.bootstrapModuleFactory (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:28512:27)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:28557:63
    at resolvePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:832:39)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:739:21
    at rejected (webpack-internal:///5760:85:89)
    at ZoneDelegate.invoke (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:386:30)
    at Object.onInvoke (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:27984:37)
    at ZoneDelegate.invoke (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:385:36)
    at Zone.run (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:143:47)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:891:38
    at ZoneDelegate.invokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:421:35)
    at Object.onInvokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:27972:37)
    at ZoneDelegate.invokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:420:40)
    at Zone.runTask (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:188:51)
    at drainMicroTaskQueue (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:601:39)
    at ZoneTask.invokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:507:25)
    at ZoneTask.invoke (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:492:52)
    at timer (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:3034:33)
    at sentryWrapped (C:\Program Files\Terminus\resources\app.asar\dist\sentry.js:1882:23)
defaultErrorLogger @ C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4229
</div>
</details>

[-1586951689145.log](https://github.com/Eugeny/terminus/files/4481013/-1586951689145.log)


Also, In every js.map in ~~/dist/
__Warnings__
```
DevTools failed to parse SourceMap: file:///C:/Users/username/scoop/apps/terminus/current/resources/app.asar/dist/xxx.js.map
```

**Comment by Eugeny** [comment]
Could you please post a dump of your `HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss` registry key?

**Comment by koumaza** [comment]
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss

<details><summary>Reg</summary><pre>
<div>
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss]
"DefaultVersion"=dword:00000002
"DefaultDistribution"="{f8c4da85-3697-4313-9bcb-681d318d9d16}"

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\{492d1999-2e4e-4289-bcde-29806fa402d6}]
"State"=dword:00000001
"DistributionName"="gavuntu-focal"
"Version"=dword:00000002
"BasePath"="V:\\WSL\\gavuntu-focal"
"Flags"=dword:0000000f
"DefaultUid"=dword:00000000

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\{6b1cc794-269d-4492-9755-9a40f3ca9027}]
"State"=dword:00000001
"DistributionName"="ArchV1"
"Version"=dword:00000002
"BasePath"="C:\\Users\\satori\\WSL\\Archver1"
"Flags"=dword:00000007
"DefaultUid"=dword:00000000

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\{70e1f924-37dc-4eb0-89ab-327c4492b077}]
"State"=dword:00000001
"DistributionName"="Alpine"
"Version"=dword:00000002
"BasePath"="C:\\Users\\satori\\AppData\\Local\\Packages\\36828agowa338.AlpineWSL_my43bytk1c4nr\\LocalState"
"Flags"=dword:0000000f
"DefaultUid"=dword:000003e8
"PackageFamilyName"="36828agowa338.AlpineWSL_my43bytk1c4nr"
"KernelCommandLine"="BOOT_IMAGE=/kernel init=/init"
"DefaultEnvironment"=hex(7):48,00,4f,00,53,00,54,00,54,00,59,00,50,00,45,00,3d,\
  00,78,00,38,00,36,00,5f,00,36,00,34,00,00,00,4c,00,41,00,4e,00,47,00,3d,00,\
  65,00,6e,00,5f,00,55,00,53,00,2e,00,55,00,54,00,46,00,2d,00,38,00,00,00,50,\
  00,41,00,54,00,48,00,3d,00,2f,00,75,00,73,00,72,00,2f,00,6c,00,6f,00,63,00,\
  61,00,6c,00,2f,00,73,00,62,00,69,00,6e,00,3a,00,2f,00,75,00,73,00,72,00,2f,\
  00,6c,00,6f,00,63,00,61,00,6c,00,2f,00,62,00,69,00,6e,00,3a,00,2f,00,75,00,\
  73,00,72,00,2f,00,73,00,62,00,69,00,6e,00,3a,00,2f,00,75,00,73,00,72,00,2f,\
  00,62,00,69,00,6e,00,3a,00,2f,00,73,00,62,00,69,00,6e,00,3a,00,2f,00,62,00,\
  69,00,6e,00,3a,00,2f,00,75,00,73,00,72,00,2f,00,67,00,61,00,6d,00,65,00,73,\
  00,3a,00,2f,00,75,00,73,00,72,00,2f,00,6c,00,6f,00,63,00,61,00,6c,00,2f,00,\
  67,00,61,00,6d,00,65,00,73,00,00,00,54,00,45,00,52,00,4d,00,3d,00,78,00,74,\
  00,65,00,72,00,6d,00,2d,00,32,00,35,00,36,00,63,00,6f,00,6c,00,6f,00,72,00,\
  00,00,00,00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\{f8c4da85-3697-4313-9bcb-681d318d9d16}]
"State"=dword:00000001
"DistributionName"="ArchV2"
"Version"=dword:00000002
"BasePath"="C:\\Users\\satori\\WSL\\Archver2"
"Flags"=dword:0000000f
"DefaultUid"=dword:00000000

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\{ff5a2ee9-9f7d-48e1-949c-1a45d01147bc}]
"State"=dword:00000001
"DistributionName"="gavuarch"
"Version"=dword:00000002
"BasePath"="V:\\WSL\\ArchGavu"
"Flags"=dword:0000000f
"DefaultUid"=dword:00000000


</div>
</details>

**Comment by Eugeny** [comment]
Just to be sure - individual distros have their keys right inside Windows\CurrentVersion? It used to be different in previous Windows builds: 
![image](https://user-images.githubusercontent.com/161476/79684827-9cdf1f80-8234-11ea-99c8-3a2ddf299079.png)

**Comment by koumaza** [comment]
I took a screenshot.
Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss
![image](https://user-images.githubusercontent.com/44153315/79692599-0f85e480-82a1-11ea-82b7-15be60a2e905.png)

Are PWSH and CMD dependent on Terminus?

**Comment by koumaza** [comment]
resolved.
I don't know why.
