### ISSUE TITLE
Cannot open any terminals

### ISSUE THREAD

**Issue by nightscape** [Eugeny/terminus#2537]
On my Windows 10 machine, there is an error in the DevTools console:
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
    at WSLShellProvider.eval (webpack-internal:///5760:4864:51)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///5760:87:71)
    at new ZoneAwarePromise (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:913:33)
    at __awaiter (webpack-internal:///5760:83:12)
    at WSLShellProvider.provide (webpack-internal:///5760:4817:16)
    at eval (webpack-internal:///5760:2875:110)
    at Array.map (<anonymous>)
    at TerminalService.eval (webpack-internal:///5760:2875:99)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///5760:87:71)
    at new ZoneAwarePromise (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:913:33)
    at __awaiter (webpack-internal:///5760:83:12)
    at TerminalService.getShells (webpack-internal:///5760:2874:16)
    at TerminalService.eval (webpack-internal:///5760:2882:39)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///5760:87:71)
    at new ZoneAwarePromise (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:913:33)
    at __awaiter (webpack-internal:///5760:83:12)
    at TerminalService.reloadShells (webpack-internal:///5760:2880:16)
    at new TerminalService (webpack-internal:///5760:2782:14)
    at C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11467:41
    at _callFactory (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22250:24)
    at _createProviderInstance (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22208:30)
    at resolveNgModuleDep (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22181:21)
    at _callFactory (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22252:32)
    at _createProviderInstance (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22208:30)
    at resolveNgModuleDep (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22166:25)
    at NgModuleRef_.get (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22787:20)
    at injectInjectorOnly (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1032:37)
    at ɵɵinject (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1037:61)
    at injectArgs (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1129:27)
    at C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11467:87
    at _callFactory (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22250:24)
    at _createProviderInstance (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22208:30)
    at resolveNgModuleDep (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22181:21)
    at _createClass (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22241:36)
    at _createProviderInstance (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22205:30)
    at initNgModule (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22135:36)
    at new NgModuleRef_ (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22775:13)
    at Object.createNgModuleRef (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22764:16)
    at NgModuleFactory_.create (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:32876:29)
    at C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:28959:47
    at ZoneDelegate.invoke (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:386:30)
    at Object.onInvoke (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:28415:37)
    at ZoneDelegate.invoke (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:385:36)
    at Zone.run (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:143:47)
    at NgZone.run (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:28310:32)
    at PlatformRef.bootstrapModuleFactory (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:28957:27)
    at C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29006:63
    at resolvePromise (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:832:39)
    at C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:739:21
    at rejected (webpack-internal:///5760:85:89)
    at ZoneDelegate.invoke (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:386:30)
    at Object.onInvoke (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:28415:37)
    at ZoneDelegate.invoke (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:385:36)
    at Zone.run (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:143:47)
    at C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:891:38
    at ZoneDelegate.invokeTask (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:421:35)
    at Object.onInvokeTask (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:28403:37)
    at ZoneDelegate.invokeTask (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:420:40)
    at Zone.runTask (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:188:51)
    at drainMicroTaskQueue (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:601:39)
    at ZoneTask.invokeTask (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:507:25)
    at ZoneTask.invoke (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:492:52)
    at timer (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\zone.js\dist\zone.js:3034:33)
    at sentryWrapped (C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\dist\sentry.js:1882:23)
defaultErrorLogger @ C:\Users\mucmaucm\scoop\apps\terminus\1.0.110\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4283
```
Subsequently I cannot open any terminals.
It might be that WSL is somehow not properly configured on my machine, but it would be great if Terminus could start properly anyway.

Is there a way to start Terminus with a breakpoint enabled?
I started it from the console with `terminus --debug` but that doesn't seem to retain the breakpoints from the last session and until I'm able to set the breakpoint, the error has already happened.

Thanks a lot for writing Terminus!

**Comment by Eugeny** [comment]
This has been fixed in the latest release.
