### ISSUE TITLE
Plugins cant be installed behind HTTPO PRoxy

### ISSUE THREAD

**Issue by MaxRink** [Eugeny/terminus#2688]
Im using a company Laptop that needs an http proxy to access the internet.
Terminus doesnt use the system pac file like it seems, so plugin installs fail

`log.service.ts:56 [pluginManager] 
FetchError {message: "request to https://registry.npmjs.org/terminus-the… reason: getaddrinfo EAI_AGAIN registry.npmjs.org", type: "system", errno: "EAI_AGAIN", code: "EAI_AGAIN", stack: "FetchError: request to https://registry.npmjs.org/…ejections (internal/process/task_queues.js:80:21)"}
message: "request to https://registry.npmjs.org/terminus-theme-windows10 failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org"
type: "system"
errno: "EAI_AGAIN"
code: "EAI_AGAIN"
level: "error"
stack: "FetchError: request to https://registry.npmjs.org/terminus-theme-windows10 failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org↵    at ClientRequest.<anonymous> (C:\Users\A92615428\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)↵    at ClientRequest.emit (events.js:210:5)↵    at TLSSocket.socketErrorListener (_http_client.js:406:9)↵    at TLSSocket.emit (events.js:210:5)↵    at emitErrorNT (internal/streams/destroy.js:92:8)↵    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)↵    at processTicksAndRejections (internal/process/task_queues.js:80:21)"
Symbol(level): "error"
Symbol(message): "{"message":"request to https://registry.npmjs.org/terminus-theme-windows10 failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org","type":"system","errno":"EAI_AGAIN","code":"EAI_AGAIN","level":"error"}"
__proto__: Error`

**Comment by rbukovansky** [comment]
Hi @Eugeny,
can somebody please take a look here? I'm not able to install plugins behind company's proxy.
Thanks,
Richard

**Comment by stibinator** [comment]
Ditto.

**Comment by qianlong1047** [comment]
Ditto.

**Comment by botboe** [comment]
Same problem here... Plugins / Updates behind the proxy would be great! Escpecially important if you want to use the config-sync-feature.

**Comment by mainzb** [comment]
Same issues.
My actual workaround is to install plugins at home and transfer them to work-environment.
Would appreciate a solution behind proxy.

**Comment by botboe** [comment]
This feature is still important.
Is there a workaround to download and install the plugins manually?

**Comment by freeNestor** [comment]
+1

**Comment by NoJokeFNA** [comment]
+1
