### ISSUE TITLE
can't open tab

### ISSUE THREAD

**Issue by csrgxtu** [Eugeny/terminus#275]
Version: 1.0.0-alpha.38
Platform: linux 4.4.0-31-generic

when i click "new terminal", nothing happens.
![image](https://user-images.githubusercontent.com/5053620/34862643-0f252716-f79e-11e7-90e1-11fb8d3688ab.png)

**Comment by Eugeny** [comment]
Please copy the error log from Settings > Dev tools > Console

**Comment by csrgxtu** [comment]
![image](https://user-images.githubusercontent.com/5053620/34865706-49624360-f7ac-11e7-8b1d-fdac875db5fc.png)

**Comment by csrgxtu** [comment]
```js
bundle.js:1445 Starting with plugins: Array[6]
bundle.js:2838 Loading community-color-schemes: /opt/Terminus/resources/builtin-plugins/terminus-community-color-schemes/dist/index.js
bundle.js:2838 Loading core: /opt/Terminus/resources/builtin-plugins/terminus-core/dist/index.js
bundle.js:2838 Loading plugin-manager: /opt/Terminus/resources/builtin-plugins/terminus-plugin-manager/dist/index.js
bundle.js:2838 Loading settings: /opt/Terminus/resources/builtin-plugins/terminus-settings/dist/index.js
bundle.js:2838 Loading ssh: /opt/Terminus/resources/builtin-plugins/terminus-ssh/dist/index.js
bundle.js:2838 Loading terminal: /opt/Terminus/resources/builtin-plugins/terminus-terminal/dist/index.js
/opt/Terminus/resources/app.asar/node_modules/@angular/core/bundles/core.umd.js:2965 Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("            <ng-template #scrollablePlaceholder></ng-template>
        </perfect-scrollbar>
        [WARNING ->]<template #nonScrollablePlaceholder [ngIf]="!scrollable"></template>
    "): ng:///AppModule/TabBodyComponent.html@4:8
Console.warn @ /opt/Terminus/resources/app.asar/node_modules/@angular/core/bundles/core.umd.js:2965
/opt/Terminus/resources/builtin-plugins/terminus-terminal/dist/index.js:20599 [tmux] started
/opt/Terminus/resources/builtin-plugins/terminus-terminal/dist/index.js:20656 [tmux] command:     set -g status off
/opt/Terminus/resources/builtin-plugins/terminus-core/dist/index.js:1431 [main] v 1.0.0-alpha.38
/opt/Terminus/resources/builtin-plugins/terminus-core/dist/index.js:1431 [updater] Checking for updates
/opt/Terminus/resources/builtin-plugins/terminus-terminal/dist/index.js:20650 [tmux] message: %session-changed $0 control
/opt/Terminus/resources/builtin-plugins/terminus-terminal/dist/index.js:20647 [tmux] block: TMuxBlock
/opt/Terminus/resources/builtin-plugins/terminus-terminal/dist/index.js:20656 [tmux] command:     set -g focus-events on
/opt/Terminus/resources/builtin-plugins/terminus-terminal/dist/index.js:20647 [tmux] block: TMuxBlock
/opt/Terminus/resources/app.asar/node_modules/@angular/core/bundles/core.umd.js:1052 ERROR Error: Uncaught (in promise): [object Object]
    at resolvePromise (/opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:770:31)
    at /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:696:17
    at rejected (/opt/Terminus/resources/builtin-plugins/terminus-terminal/dist/index.js:20551:89)
    at ZoneDelegate.invoke (/opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:391:26)
    at Object.onInvoke (/opt/Terminus/resources/app.asar/node_modules/@angular/core/bundles/core.umd.js:3922:33)
    at ZoneDelegate.invoke (/opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:390:32)
    at Zone.run (/opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:141:43)
    at /opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:818:57
    at ZoneDelegate.invokeTask (/opt/Terminus/resources/app.asar/node_modules/zone.js/dist/zone.js:424:31)
    at Object.onInvokeTask (/opt/Terminus/resources/app.asar/node_modules/@angular/core/bundles/core.umd.js:3913:33)
defaultErrorLogger @ /opt/Terminus/resources/app.asar/node_modules/@angular/core/bundles/core.umd.js:1052
/opt/Terminus/resources/builtin-plugins/terminus-core/dist/index.js:1431 [updater] No updates
```

**Comment by Eugeny** [comment]
Try disabling Persistence under Settings > Terminal > Behaviour

**Comment by csrgxtu** [comment]
@Eugeny 
tkx very much, it worked.
