### ISSUE TITLE
SSH - Failed to load key: bad permissions

### ISSUE THREAD

**Issue by shd2h** [Eugeny/terminus#3326]
Version: 1.0.126
Platform: win32 10.0.19041
Plugins: none

This appears to be the same as issues #2340, #2218, #2209 and #2201; but with a more recent version of Terminus.
Initiating an ssh connection that uses a saved private key for authentication causes the connection to hang at the "connecting" stage, and no obvious error is generated:
```
 SSH  Connecting to 192.168.XXX.XXX
Loading private key from  C:\Users\user\Documents\ssh_keys\ssh_keyname 
■ Connecting
```
Connecting using a password instead of a private key works fine.

The devtools debugger shows the following two errors after triggering the connection attempt; first a "file not found" and then an ssh-key bad permissions error:

```
C:\Users\user\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:6027 Matched hotkey ssh
index.html?1:1 Autofocus processing was blocked because a document already has a focused element.
/C:/Users/user/AppData/Local/Programs/Terminus/resources/app.asar/dist/[object%20Module]:1 GET file:///C:/Users/user/AppData/Local/Programs/Terminus/resources/app.asar/dist/[object%20Module] net::ERR_FILE_NOT_FOUND
C:\Users\user\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:5383 
[ssh] Loading private key from  C:\Users\user\Documents\ssh_keys\ssh_keyname 
C:\Users\user\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4312 ERROR Error: Uncaught (in promise): Error: Command failed: C:\Users\user\AppData\Local\Programs\Terminus\resources\extras\ssh-keygen\ssh-keygen.exe -p -P  -N  -m PEM -f C:\Users\user\AppData\Local\Temp\f-2021011-14384-x4cz0.akqkja
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for 'C:\\Users\\user\\AppData\\Local\\Temp\\f-2021011-14384-x4cz0.akqkja' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Failed to load key C:\\Users\\user\\AppData\\Local\\Temp\\f-2021011-14384-x4cz0.akqkja: bad permissions

Error: Command failed: C:\Users\user\AppData\Local\Programs\Terminus\resources\extras\ssh-keygen\ssh-keygen.exe -p -P  -N  -m PEM -f C:\Users\user\AppData\Local\Temp\f-2021011-14384-x4cz0.akqkja
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for 'C:\\Users\\user\\AppData\\Local\\Temp\\f-2021011-14384-x4cz0.akqkja' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Failed to load key C:\\Users\\user\\AppData\\Local\\Temp\\f-2021011-14384-x4cz0.akqkja: bad permissions

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    at resolvePromise (C:\Users\user\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1250:35)
    at C:\Users\user\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1157:21
    at rejected (C:\Users\user\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-ssh\dist\index.js:1513:89)
    at ZoneDelegate.invoke (C:\Users\user\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:395:30)
    at Object.onInvoke (C:\Users\user\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:28315:37)
    at ZoneDelegate.invoke (C:\Users\user\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:394:56)
    at Zone.run (C:\Users\user\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:155:47)
    at C:\Users\user\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1313:38
    at ZoneDelegate.invokeTask (C:\Users\user\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:429:35)
    at Object.onInvokeTask (C:\Users\user\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:28303:37)
    at ZoneDelegate.invokeTask (C:\Users\user\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:428:64)
    at Zone.runTask (C:\Users\user\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:200:51)
    at drainMicroTaskQueue (C:\Users\user\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:615:39)
defaultErrorLogger @ C:\Users\user\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4312
```

I've tried using older versions of Terminus (via the portable zip downloads) that I know worked previously, but weirdly I run into the same error. I went as far back as v1.0.122 with no success.
Please let me know if there's any other info I can provide to help debug this.

Thanks.

**Comment by shd2h** [comment]
I was able to get to the bottom of this in the end; here's the troubleshooting trail in-case anyone else runs into a similar situation in the future.

Despite a clean install (I wiped the config dir under C:\Users\USERNAME\AppData\Roaming\terminus) the problem persisted in v1.0.127, and I rolled all the way back to v1.0.120 with no change in symptoms.
I was unable to reproduce this on a second machine at the same windows code level, which pointed the finger at it being a local config problem.
I found that despite the permissions of files inside the C:\Users\USERNAME\Local\Temp dir being okay, the directory itself had somehow had it's permissions completely wiped:

![missing_permissions](https://user-images.githubusercontent.com/46810384/104970099-4cbf0480-59e2-11eb-8916-063b985f8c98.png)

After I restored these (made them match the surrounding folders), everything started to work again.

Closing this out as all is now resolved, thanks.
