### ISSUE TITLE
error at npm install

### ISSUE THREAD

**Issue by diegopego** [Eugeny/terminus#337]
windows 7 sp1 x64
The follwing error log is generated by 
npm install

If  I insist and run the command

`node scripts\install-deps.js`
I got the following error:

```
S:\devel\experimentos\electron\terminus\scripts\install-deps.js:26
  for (let x of vars.builtinPlugins) {
       ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet sup
ported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
[npm-debug.log](https://github.com/Eugeny/terminus/files/1972773/npm-debug.log)

```

**Comment by Eugeny** [comment]
Please upgrade your NodeJS installation
