### ISSUE TITLE
Bug at History restored

### ISSUE THREAD

**Issue by evalexp** [Eugeny/terminus#3427]
Version: 1.0.130
Platform: win32 10.0.18363
Plugins: none

As I open my terminus, I wait for a while, it also show me:

```cmd
* History restored 
```

and never let me in the shell, I hope this problem could be fixed quickly.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by evalexp** [comment]
> Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Eugeny/terminus](https://github.com/Eugeny/terminus)**A terminal for a more modern age. Contribute to Eugeny/terminus development by creating an account on GitHub.

ok, and here is the logs:

```javascript
D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:6479 ERROR Error: Cannot create process, error code: 267
    at new WindowsPtyAgent (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\@terminus-term\node-pty\lib\windowsPtyAgent.js:104:43)
    at new WindowsTerminal (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\@terminus-term\node-pty\lib\windowsTerminal.js:50:24)
    at spawn (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\@terminus-term\node-pty\lib\index.js:28:12)
    at Object.mod.spawn (D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:74141:20)
    at Session.start (D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:13161:73)
    at SessionsService.addSession (D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:13356:17)
    at TerminalTabComponent.initializeSession (D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:10314:23)
    at SafeSubscriber._next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:10309:18)
    at SafeSubscriber.__tryOrUnsub (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:143:22)
    at Subscriber._next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\operators\throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at TakeSubscriber._next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\operators\take.js:54:30)
    at TakeSubscriber.Subscriber.next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Subject.next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subject.js:60:25)
    at TerminalTabComponent.<anonymous> (D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:8857:32)
    at Generator.next (<anonymous>)
    at D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:3434:71
    at new ZoneAwarePromise (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\zone.js\dist\zone.js:1335:33)
    at __awaiter (D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:3430:12)
    at SafeSubscriber._next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:8854:185)
    at SafeSubscriber.__tryOrUnsub (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:143:22)
    at Subscriber._next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\operators\throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at TakeSubscriber._next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\operators\take.js:54:30)
    at TakeSubscriber.Subscriber.next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at ReplaySubject.Subject.next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subject.js:60:25)
    at ReplaySubject.nextInfiniteTimeWindow (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\ReplaySubject.js:50:31)
    at D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:12222:25
    at e.fire (D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:69711:179763)
    at D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:69711:179957
    at e.fire (D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:69711:179763)
    at r.resize (D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:69711:281342)
    at t.resize (D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:69711:176313)
    at t.resize (D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:69711:61441)
    at e.resize (D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:69711:78238)
    at XTermFrontend.resizeHandler (D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:12274:36)
    at XTermFrontend.attach (D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:12303:14)
    at SafeSubscriber._next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:8888:35)
    at SafeSubscriber.__tryOrUnsub (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:143:22)
    at Subscriber._next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\operators\throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
defaultErrorLogger @ D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:6479
D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:6479 ERROR TypeError: Cannot read property '_writable' of undefined
    at Session.resize (D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:13209:22)
    at D:\Applications\Scoop\apps\terminus\1.0.134\resources\builtin-plugins\terminus-terminal\dist\index.js:8868:77
    at ZoneDelegate.invokeTask (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\zone.js\dist\zone.js:429:35)
    at Object.onInvokeTask (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29190:37)
    at ZoneDelegate.invokeTask (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\zone.js\dist\zone.js:428:64)
    at Zone.runTask (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\zone.js\dist\zone.js:200:51)
    at ZoneTask.invokeTask (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\zone.js\dist\zone.js:511:38)
    at ZoneTask.invoke (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\zone.js\dist\zone.js:500:52)
    at timer (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\node_modules\zone.js\dist\zone.js:3059:33)
    at sentryWrapped (D:\Applications\Scoop\apps\terminus\1.0.134\resources\app.asar\dist\sentry.js:4210:23)
```

**Comment by Eugeny** [comment]
Thanks! Which shell is selected as default? What's its path? You can also copy the path directly from the console - it should be logged right above the error along with other session parameters

**Comment by evalexp** [comment]
> Thanks! Which shell is selected as default? What's its path? You can also copy the path directly from the console - it should be logged right above the error along with other session parameters

well, powershell V5.1.18362.1171 is my default shell, and its path should be **C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe**,

**Comment by Eugeny** [comment]
Thanks - could you please also copy the complete session parameters object? It should look like this: 
![image](https://user-images.githubusercontent.com/161476/108605046-f44c9f80-73b1-11eb-88e7-897de74e8314.png)

**Comment by evalexp** [comment]
> Thanks - could you please also copy the complete session parameters object? It should look like this:
> ![image](https://user-images.githubusercontent.com/161476/108605046-f44c9f80-73b1-11eb-88e7-897de74e8314.png)

ok, and here is the images
![image](https://user-images.githubusercontent.com/72970177/108614376-fc015800-7434-11eb-8137-abd8137164a4.png)

**Comment by harunyasar** [comment]
It also appears when a window is split.

**Comment by M-r-A** [comment]
Version: 1.0.209
Platform: Windows x64 10.0.22631
Plugins: none
Frontend: xterm-webgl

@Eugeny I have the same issue with the PowerShell tab. After a system update with a forced restart, probably around 06:30, I started Tabby (which was open at the time of the forced restart). The tab with PowerShell is stuck on `* History restored`. 

Restarting Tabby doesn't help recover this tab; it just adds a new `* History restored` line. Starting a new tab with PowerShell makes it stuck with empty screen.

- Which shell is selected as default?
"C:\WINDOWS\system32\wsl.exe" (WSL / Default distro). Version Ubuntu 22.04

- Which shell is selected for the tab with error?
"powershell.exe" (PowerShell). Version 5.1.22621.3880

- Could you please also copy the complete session parameters object?
I don't see `Using session options` line in DevTools console.

- Last command executed for tab with error?
`PS C:\Users\[username]> bash /mnt/d/Downloads/cloud_sql_script_windows.sh`

Screenshot after 3 Tabby restarts:
![image](https://github.com/Eugeny/tabby/assets/5612696/7ba7849b-c11e-44da-badb-d93634dbc0bf)

Screenshot with new PowerShell tab:
![image](https://github.com/Eugeny/tabby/assets/5612696/d8d3ddef-880d-4e74-aafe-171564fedcc9)


DevTools console logs:
```text
[hostApp] CLI handler matched: AutoOpenTabCLIHandler

C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:27529 Unhandled exception: Error: Cannot create process, error code: 267
    at new WindowsPtyAgent (C:\Program Files\Tabby\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:112:43)
    at new WindowsTerminal (C:\Program Files\Tabby\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:51:24)
    at Object.spawn (C:\Program Files\Tabby\resources\app.asar\node_modules\node-pty\lib\index.js:29:12)
    at new d (C:\Program Files\Tabby\resources\app.asar\dist\webpack:\tabby\lib\pty.ts:96:37)
    at IpcMainImpl.<anonymous> (C:\Program Files\Tabby\resources\app.asar\dist\webpack:\tabby\lib\pty.ts:147:29)
    at IpcMainImpl.emit (node:events:514:28)
    at IpcMainImpl.emit (node:domain:489:12)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89402)
    at WebContents.emit (node:events:514:28)
    at WebContents.emit (node:domain:489:12)
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-core\dist\index.js:27529
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:32602
emit @ node:events:514
onMessage @ node:electron/js2c/renderer_init:2

C:\Program Files\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:3021 Could not read working directory: Error: NtQueryInformationProcess failed to fetch ProcessBasicInformation-1073741816
    at getWorkingDirectoryFromPID (C:\Program Files\Tabby\resources\app.asar\node_modules\native-process-working-directory\index.js:25:36)
    at ElectronPTYProxy.<anonymous> (C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:37635:93)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:27896:24)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:127:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:171:47)
    at drainMicroTaskQueue (zone.js:581:35)

C:\Program Files\Tabby\resources\builtin-plugins\tabby-local\dist\index.js:3021 Could not read working directory: Error: NtQueryInformationProcess failed to fetch ProcessBasicInformation-1073741816
    at getWorkingDirectoryFromPID (C:\Program Files\Tabby\resources\app.asar\node_modules\native-process-working-directory\index.js:25:36)
    at ElectronPTYProxy.<anonymous> (C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:37635:93)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Tabby\resources\builtin-plugins\tabby-electron\dist\index.js:27896:24)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:127:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:171:47)
    at drainMicroTaskQueue (zone.js:581:35)
    at invokeTask (zone.js:487:21)
    at ZoneTask.invoke (zone.js:472:48)
    at data.args.<computed> (zone.js:2335:32)
    at sentryWrapped (helpers.ts:87:17)
```
