### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by SolarAquarion** [Eugeny/terminus#353]
```
yarn run build                    ✔  1238  11:45:49   
yarn run v1.7.0
$ webpack --color --config app/webpack.config.js && webpack --color --config terminus-core/webpack.config.js && webpack --color --config terminus-settings/webpack.config.js && webpack --color --config terminus-terminal/webpack.config.js && webpack --color --config terminus-settings/webpack.config.js && webpack --color --config terminus-plugin-manager/webpack.config.js && webpack --color --config terminus-community-color-schemes/webpack.config.js && webpack --color --config terminus-ssh/webpack.config.js

[at-loader] Using typescript@2.2.2 from typescript and "tsconfig.json" from /home/solaraquarion/pkgbuild/terminus-terminal/src/terminus-1.0.0-alpha.47/app/tsconfig.json.

(node:14293) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

[at-loader] Checking started in a separate process...

[at-loader] Ok, 0.345 sec.
Hash: b6617ce30c80e75cdf4f
Version: webpack 3.10.0
Time: 2186ms
                                    Asset       Size  Chunks                    Chunk Names
  fonts/SourceSansPro-SemiboldIt.otf.woff    54.3 kB          [emitted]         
                               index.html  560 bytes          [emitted]         
  fonts/SourceSansPro-ExtraLight.otf.woff     125 kB          [emitted]         
       fonts/SourceSansPro-ExtraLight.otf     227 kB          [emitted]         
       fonts/SourceSansPro-ExtraLight.ttf     292 kB          [emitted]  [big]  
     fonts/SourceSansPro-ExtraLightIt.eot     104 kB          [emitted]         
fonts/SourceSansPro-ExtraLightIt.otf.woff    50.1 kB          [emitted]         
     fonts/SourceSansPro-ExtraLightIt.otf    78.7 kB          [emitted]         
     fonts/SourceSansPro-ExtraLightIt.ttf     104 kB          [emitted]         
            fonts/SourceSansPro-Light.eot     294 kB          [emitted]  [big]  
       fonts/SourceSansPro-Light.otf.woff     130 kB          [emitted]         
            fonts/SourceSansPro-Light.otf     231 kB          [emitted]         
            fonts/SourceSansPro-Light.ttf     293 kB          [emitted]  [big]  
          fonts/SourceSansPro-LightIt.eot     104 kB          [emitted]         
     fonts/SourceSansPro-LightIt.otf.woff    52.3 kB          [emitted]         
          fonts/SourceSansPro-LightIt.otf    79.7 kB          [emitted]         
          fonts/SourceSansPro-LightIt.ttf     104 kB          [emitted]         
          fonts/SourceSansPro-Regular.eot     294 kB          [emitted]  [big]  
     fonts/SourceSansPro-Regular.otf.woff     133 kB          [emitted]         
          fonts/SourceSansPro-Regular.otf     235 kB          [emitted]         
          fonts/SourceSansPro-Regular.ttf     294 kB          [emitted]  [big]  
               fonts/SourceSansPro-It.eot     104 kB          [emitted]         
          fonts/SourceSansPro-It.otf.woff    53.9 kB          [emitted]         
               fonts/SourceSansPro-It.otf    81.7 kB          [emitted]         
               fonts/SourceSansPro-It.ttf     104 kB          [emitted]         
         fonts/SourceSansPro-Semibold.eot     293 kB          [emitted]  [big]  
    fonts/SourceSansPro-Semibold.otf.woff     135 kB          [emitted]         
         fonts/SourceSansPro-Semibold.otf     238 kB          [emitted]         
         fonts/SourceSansPro-Semibold.ttf     292 kB          [emitted]  [big]  
       fonts/SourceSansPro-SemiboldIt.eot     104 kB          [emitted]         
       fonts/SourceSansPro-ExtraLight.eot     292 kB          [emitted]  [big]  
       fonts/SourceSansPro-SemiboldIt.otf    82.6 kB          [emitted]         
       fonts/SourceSansPro-SemiboldIt.ttf     103 kB          [emitted]         
             fonts/SourceSansPro-Bold.eot     292 kB          [emitted]  [big]  
        fonts/SourceSansPro-Bold.otf.woff     136 kB          [emitted]         
             fonts/SourceSansPro-Bold.otf     239 kB          [emitted]         
             fonts/SourceSansPro-Bold.ttf     292 kB          [emitted]  [big]  
           fonts/SourceSansPro-BoldIt.eot     103 kB          [emitted]         
      fonts/SourceSansPro-BoldIt.otf.woff    54.3 kB          [emitted]         
           fonts/SourceSansPro-BoldIt.otf    82.5 kB          [emitted]         
           fonts/SourceSansPro-BoldIt.ttf     103 kB          [emitted]         
            fonts/SourceSansPro-Black.eot     290 kB          [emitted]  [big]  
       fonts/SourceSansPro-Black.otf.woff     132 kB          [emitted]         
            fonts/SourceSansPro-Black.otf     238 kB          [emitted]         
            fonts/SourceSansPro-Black.ttf     290 kB          [emitted]  [big]  
          fonts/SourceSansPro-BlackIt.eot     103 kB          [emitted]         
     fonts/SourceSansPro-BlackIt.otf.woff    54.2 kB          [emitted]         
          fonts/SourceSansPro-BlackIt.otf    83.5 kB          [emitted]         
          fonts/SourceSansPro-BlackIt.ttf     103 kB          [emitted]         
            fonts/fontawesome-webfont.eot     166 kB          [emitted]         
          fonts/fontawesome-webfont.woff2    77.2 kB          [emitted]         
           fonts/fontawesome-webfont.woff      98 kB          [emitted]         
            fonts/fontawesome-webfont.ttf     166 kB          [emitted]         
           images/fontawesome-webfont.svg     444 kB          [emitted]  [big]  
                          images/logo.svg    3.54 kB          [emitted]         
                                bundle.js     156 kB       0  [emitted]         bundle
                               preload.js     208 kB       1  [emitted]         preload
                          index.ignore.js    3.12 kB       2  [emitted]         index.ignore
                            bundle.js.map     155 kB       0  [emitted]         bundle
                           preload.js.map     238 kB       1  [emitted]         preload
                      index.ignore.js.map    2.78 kB       2  [emitted]         index.ignore
  [52] ../node_modules/file-loader?name=index.html!../node_modules/val-loader!../node_modules/pug-html-loader/lib!./index.pug 56 bytes {2} [built]
  [53] ./src/entry.preload.ts 1.19 kB {1} [built]
 [114] ./src/preload.scss 1.05 kB {1} [built]
 [115] ../node_modules/css-loader!../node_modules/sass-loader/lib/loader.js!./src/preload.scss 1.24 kB {1} [built]
 [116] ./assets/logo.svg 61 bytes {1} [built]
 [124] ./src/entry.ts 2.48 kB {0} [built]
 [170] ./src/toastr.scss 1.05 kB {0} [built]
 [171] ../node_modules/css-loader!../node_modules/sass-loader/lib/loader.js!./src/toastr.scss 476 bytes {0} [built]
 [173] ./src/app.module.ts 1.73 kB {0} [built]
 [177] ./src/plugins.ts 6.38 kB {0} [built]
 [181] ./node_modules/any-promise 160 bytes {0} [built]
    + 182 hidden modules

WARNING in ./node_modules/any-promise/register.js
24:14-37 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/any-promise/register.js
 @ ./node_modules/any-promise/index.js
 @ ./node_modules/mz/fs.js
 @ ./src/plugins.ts
 @ ./src/entry.ts

[at-loader] Using typescript@2.2.2 from typescript and "tsconfig.json" from /home/solaraquarion/pkgbuild/terminus-terminal/src/terminus-1.0.0-alpha.47/terminus-core/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 3 errors
Hash: cee2ebc00f0e8bf2f984
Version: webpack 3.10.0
Time: 2023ms
       Asset    Size  Chunks             Chunk Names
    index.js  160 kB       0  [emitted]  main
index.js.map  165 kB       0  [emitted]  main
   [2] ./src/services/config.service.ts 5.16 kB {0} [built]
   [6] ./src/services/log.service.ts 2.86 kB {0} [built]
   [7] ./src/services/hostApp.service.ts 4.43 kB {0} [built]
   [9] ./src/services/app.service.ts 5.89 kB {0} [built]
  [11] ./src/api/index.ts 1.94 kB {0} [built]
  [12] ./src/api/configProvider.ts 242 bytes {0} [built]
  [14] ./src/services/hotkeys.service.ts 8.69 kB {0} [built]
  [15] ./src/api/hotkeyProvider.ts 204 bytes {0} [built]
  [16] ./src/services/docking.service.ts 4.4 kB {0} [built]
  [17] ./src/services/themes.service.ts 2.46 kB {0} [built]
  [18] ./src/api/theme.ts 121 bytes {0} [built]
  [24] ./src/services/tabRecovery.service.ts 3.77 kB {0} [built]
  [26] ./src/services/touchbar.service.ts 4.29 kB {0} [built]
  [27] ./src/services/updater.service.ts 2.7 kB {0} [built]
  [30] ./src/index.ts 5.2 kB {0} [built]
    + 66 hidden modules

ERROR in ../node_modules/css-loader!../node_modules/sass-loader/lib/loader.js!./src/theme.compact.scss
Module build failed: 
@import '~bootstrap/scss/bootstrap.scss';
^
      File to import not found or unreadable: ~bootstrap/scss/bootstrap.scss.
Parent style sheet: /home/solaraquarion/pkgbuild/terminus-terminal/src/terminus-1.0.0-alpha.47/terminus-core/src/theme.scss
      in /home/solaraquarion/pkgbuild/terminus-terminal/src/terminus-1.0.0-alpha.47/terminus-core/src/theme.scss (line 90, column 1)
 @ ./src/theme.compact.scss 2:21-138
 @ ./src/theme.ts
 @ ./src/index.ts

ERROR in ../node_modules/css-loader!../node_modules/sass-loader/lib/loader.js!./src/theme.scss
Module build failed: 
@import '~bootstrap/scss/bootstrap.scss';
^
      File to import not found or unreadable: ~bootstrap/scss/bootstrap.scss.
Parent style sheet: stdin
      in /home/solaraquarion/pkgbuild/terminus-terminal/src/terminus-1.0.0-alpha.47/terminus-core/src/theme.scss (line 90, column 1)
 @ ./src/theme.scss 2:21-130
 @ ./src/theme.ts
 @ ./src/index.ts

ERROR in ./src/services/updater.service.ts
Module not found: Error: Can't resolve 'axios' in '/home/solaraquarion/pkgbuild/terminus-terminal/src/terminus-1.0.0-alpha.47/terminus-core/src/services'
 @ ./src/services/updater.service.ts 20:16-32
 @ ./src/index.ts

ERROR in ./src/services/config.service.ts
Module not found: Error: Can't resolve 'core-js/es7/reflect' in '/home/solaraquarion/pkgbuild/terminus-terminal/src/terminus-1.0.0-alpha.47/terminus-core/src/services'
 @ ./src/services/config.service.ts 23:16-46
 @ ./src/index.ts

ERROR in ./src/index.ts
Module not found: Error: Can't resolve 'ngx-perfect-scrollbar' in '/home/solaraquarion/pkgbuild/terminus-terminal/src/terminus-1.0.0-alpha.47/terminus-core/src'
 @ ./src/index.ts 17:32-64

ERROR in ./src/index.ts
Module not found: Error: Can't resolve 'perfect-scrollbar/dist/css/perfect-scrollbar.css' in '/home/solaraquarion/pkgbuild/terminus-terminal/src/terminus-1.0.0-alpha.47/terminus-core/src'
 @ ./src/index.ts 44:0-59

ERROR in [at-loader] ./terminus-core/src/index.ts:6:40 
    TS2307: Cannot find module 'ngx-perfect-scrollbar'.

ERROR in [at-loader] ./terminus-core/src/services/log.service.ts:3:26 
    TS2307: Cannot find module 'winston'.

ERROR in [at-loader] ./terminus-core/src/services/updater.service.ts:1:19 
    TS2307: Cannot find module 'axios'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run build  7.55s user 0.42s system 160% cpu 4.977 total
```
i think you need to add more modules

**Comment by SolarAquarion** [comment]
```
ERROR in ../node_modules/css-loader!../node_modules/sass-loader/lib/loader.js!./src/theme.compact.scss
Module build failed: 
@import '~bootstrap/scss/bootstrap.scss';
^
      File to import not found or unreadable: ~bootstrap/scss/bootstrap.scss.
Parent style sheet: /home/solaraquarion/pkgbuild/terminus-terminal/src/terminus-1.0.0-alpha.47/terminus-core/src/theme.scss
      in /home/solaraquarion/pkgbuild/terminus-terminal/src/terminus-1.0.0-alpha.47/terminus-core/src/theme.scss (line 90, column 1)
 @ ./src/theme.compact.scss 2:21-138
 @ ./src/theme.ts
 @ ./src/index.ts

ERROR in ../node_modules/css-loader!../node_modules/sass-loader/lib/loader.js!./src/theme.scss
Module build failed: 
@import '~bootstrap/scss/bootstrap.scss';
^
      File to import not found or unreadable: ~bootstrap/scss/bootstrap.scss.
Parent style sheet: stdin
      in /home/solaraquarion/pkgbuild/terminus-terminal/src/terminus-1.0.0-alpha.47/terminus-core/src/theme.scss (line 90, column 1)
 @ ./src/theme.scss 2:21-130
 @ ./src/theme.ts
 @ ./src/index.ts

ERROR in ./src/services/updater.service.ts
Module not found: Error: Can't resolve 'axios' in '/home/solaraquarion/pkgbuild/terminus-terminal/src/terminus-1.0.0-alpha.47/terminus-core/src/services'
 @ ./src/services/updater.service.ts 20:16-32
 @ ./src/index.ts

ERROR in ./src/services/config.service.ts
Module not found: Error: Can't resolve 'core-js/es7/reflect' in '/home/solaraquarion/pkgbuild/terminus-terminal/src/terminus-1.0.0-alpha.47/terminus-core/src/services'
 @ ./src/services/config.service.ts 23:16-46
 @ ./src/index.ts

ERROR in ./src/index.ts
Module not found: Error: Can't resolve 'ngx-perfect-scrollbar' in '/home/solaraquarion/pkgbuild/terminus-terminal/src/terminus-1.0.0-alpha.47/terminus-core/src'
 @ ./src/index.ts 17:32-64

ERROR in ./src/index.ts
Module not found: Error: Can't resolve 'perfect-scrollbar/dist/css/perfect-scrollbar.css' in '/home/solaraquarion/pkgbuild/terminus-terminal/src/terminus-1.0.0-alpha.47/terminus-core/src'
 @ ./src/index.ts 44:0-59

ERROR in [at-loader] ./terminus-core/src/index.ts:63:32 
    TS2339: Property 'forRoot' does not exist on type 'typeof PerfectScrollbarModule'.
```

**Comment by Eugeny** [comment]
Make sure to install the sub-dependencies first (./scripts/install-deps.js)

**Comment by SolarAquarion** [comment]
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'shelljs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/solaraquarion/pkgbuild/terminus-terminal/src/terminus/scripts/install-deps.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)

**Comment by Eugeny** [comment]
shelljs is included in the root package.json. Make sure Yarn succeeds installing the root deps first.

**Comment by SolarAquarion** [comment]
I'm trying to do a source build but, the terminal isn't loading.  I'm getting a font failure
