### ISSUE TITLE
yarn error <path-to-terminus-code>/node_modules/@sentry/cli: Command failed

### ISSUE THREAD

**Issue by clarkwang** [Eugeny/terminus#3533]
I was following the HACKING guide and hit the following error:

~~~
[...]
warning validate-npm-package-name@3.0.0: Invalid bin field for "validate-npm-package-name".
warning wrappy@1.0.2: Invalid bin field for "wrappy".
[4/4] 🔨  Building fresh packages...
[-/8] ⠐ waiting...
[2/8] ⠐ @sentry/cli
[7/8] ⠐ node-sass
[6/8] ⠐ electron
error /Users/clarkw/WHJM/data/Terminus/node_modules/@sentry/cli: Command failed.
Exit code: 1
~~~

**Comment by clarkwang** [comment]
Cleaned the local dir and tried again. This time another `Command failed`:

~~~
[...]
warning wrappy@1.0.2: Invalid bin field for "wrappy".
[4/4] 🔨  Building fresh packages...
[-/8] ⠐ waiting...
[-/8] ⠐ waiting...
[6/8] ⠐ node-sass
[7/8] ⠐ electron
error /Users/clarkw/WHJM/data/Terminus/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/clarkw/WHJM/data/Terminus/node_modules/electron
Output:
RequestError: socket hang up
    at ClientRequest.<anonymous> (/Users/clarkw/WHJM/data/Terminus/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/Users/clarkw/WHJM/data/Terminus/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketOnEnd (_http_client.js:493:9)
~~~

**Comment by clarkwang** [comment]
Don't know exactly how but managed to make it work.

**Comment by Eugeny** [comment]
Looks like it failed while downloading Electron - likely a connection fluke
