### ISSUE TITLE
./scripts/build-native.js fails in Linux

### ISSUE THREAD

**Issue by genfes** [Eugeny/terminus#3633]
Hi,

I use the aur install package to install terminus: https://aur.archlinux.org/packages/terminus-terminal/
It calls scripts/build-native.js, but it failes.

Here the output:

```
...
/tmp/trizen-jack/terminus-terminal/src/terminus/scripts/build-native.js:11
        arch: process.env.ARCH ?? process.arch,
                                ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
:: Unable to build terminus-terminal - makepkg exited with code: 4
...
```

**Comment by Eugeny** [comment]
The build script needs a newer Node version than the one you've got.
