### ISSUE TITLE
build doesn't work on linux

### ISSUE THREAD

**Issue by uqlel** [Eugeny/terminus#3700]
hello,
when i try to run commands for package installation from HACKING.md on Ubuntu, it throws error and it isn't creating directory app/dist. I tried also running as root.
yarn v1.22.5
os kubuntu 20.04
nodejs v14.16.1
npm v6.14.12
error:
```
make: Entering directory '/home/uqlel/Dokumenty/projekty/terminus/app/node_modules/fontmanager-redux/build'
  CXX(target) Release/obj.target/fontmanager/src/FontManager.o
  CXX(target) Release/obj.target/fontmanager/src/FontManagerLinux.o
../src/FontManagerLinux.cc:1:10: fatal error: fontconfig/fontconfig.h: No such file or directory
    1 | #include <fontconfig/fontconfig.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [fontmanager.target.mk:116: Release/obj.target/fontmanager/src/FontManagerLinux.o] Error 1
make: Leaving directory '/home/uqlel/Dokumenty/projekty/terminus/app/node_modules/fontmanager-redux/build'
Error: node-gyp failed to rebuild '/home/uqlel/Dokumenty/projekty/terminus/app/node_modules/fontmanager-redux'.
Error: `make` failed with exit code: 2


    at ModuleRebuilder.rebuildNodeGypModule (/home/uqlel/Dokumenty/projekty/terminus/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Rebuilder.rebuildModuleAt (/home/uqlel/Dokumenty/projekty/terminus/node_modules/electron-rebuild/lib/src/rebuild.js:190:9)
    at async Rebuilder.rebuild (/home/uqlel/Dokumenty/projekty/terminus/node_modules/electron-rebuild/lib/src/rebuild.js:152:17)
```
 sorry for my bad english

**Comment by Eugeny** [comment]
You need the `libfontconfig-dev` package

**Comment by uqlel** [comment]
do i need to run as root?
