### ISSUE TITLE
Automatic Updates don't work

### ISSUE THREAD

**Issue by NEWOLONOS** [Eugeny/terminus#3707]
I turned "Automatic Updates" on, but it won't install updates.

**Comment by DeviantUK** [comment]
The check for updates button doesn't work either.

This appears in the debug log when starting Terminus:
```
[updater] Error: Can not find Squirrel
    at AutoUpdater.method [as checkForUpdates] (electron/js2c/browser_init.js:17:1405)
    at handler (C:\Program Files\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@electron\remote\dist\src\main\server.js:454:64)
    at IpcMainImpl.<anonymous> (C:\Program Files\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@electron\remote\dist\src\main\server.js:313:27)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10351)
    at Object.emit (events.js:315:20)
    at Object.apply [as emit] (domain.js:467:12)
    at Object.n.emit (C:\Program Files\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@sentry\electron\dist\main\integrations\electron.js:66:25)
doLog @ C:\Program Files\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:28346
```
And this appears when clicking the check for updates button:
```
ERROR Error: Uncaught (in promise): Error: Can not find Squirrel
Error: Can not find Squirrel
    at AutoUpdater.method [as checkForUpdates] (electron/js2c/browser_init.js:17:1405)
    at handler (C:\Program Files\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@electron\remote\dist\src\main\server.js:454:64)
    at IpcMainImpl.<anonymous> (C:\Program Files\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@electron\remote\dist\src\main\server.js:313:27)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10351)
    at Object.emit (events.js:315:20)
    at Object.apply [as emit] (domain.js:467:12)
    at Object.n.emit (C:\Program Files\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@sentry\electron\dist\main\integrations\electron.js:66:25)
    at resolvePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1255:35)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1162:21
    at rejected (C:\Program Files\Terminus\resources\builtin-plugins\terminus-settings\dist\index.js:3372:89)
    at ZoneDelegate.invoke (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:400:30)
    at Object.onInvoke (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29203:37)
    at ZoneDelegate.invoke (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:399:56)
    at Zone.run (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:160:47)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1318:38
    at ZoneDelegate.invokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:434:35)
    at Object.onInvokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29190:37)
    at ZoneDelegate.invokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:433:64)
    at Zone.runTask (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:205:51)
    at drainMicroTaskQueue (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:620:39)
defaultErrorLogger @ C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:6479
ErrorHandler.handleError @ C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:6527
next @ C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29814
schedulerFn @ C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:26572
SafeSubscriber.__tryOrUnsub @ C:\Program Files\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:205
SafeSubscriber.next @ C:\Program Files\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:143
Subscriber._next @ C:\Program Files\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:89
Subscriber.next @ C:\Program Files\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66
Subject.next @ C:\Program Files\Terminus\resources\app.asar\node_modules\rxjs\internal\Subject.js:60
EventEmitter_.emit @ C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:26562
(anonymous) @ C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29229
ZoneDelegate.invoke @ C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:400
Zone.run @ C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:160
NgZone.runOutsideAngular @ C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29131
onHandleError @ C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29229
ZoneDelegate.handleError @ C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:404
Zone.runGuarded @ C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:174
_loop_2 @ C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1113
api.microtaskDrainDone @ C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1125
drainMicroTaskQueue @ C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:627
Promise.then (async)
scheduleMicroTask @ C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:603
ZoneDelegate.scheduleTask @ C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:424
onScheduleTask @ C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:311
ZoneDelegate.scheduleTask @ C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:414
Zone.scheduleTask @ C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:248
Zone.scheduleMicroTask @ C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:268
scheduleResolveOrReject @ C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1308
resolvePromise @ C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1246
(anonymous) @ C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1162
onError @ C:\Program Files\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:33207
apply @ C:\Program Files\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:2715
(anonymous) @ C:\Program Files\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:3100
(anonymous) @ C:\Program Files\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:3082
emit @ events.js:327
onMessage @ electron/js2c/renderer_init.js:93
```

Windows 10H2 / Terminus 1.0.137

**Comment by hanmala123** [comment]
I also encountered this problem.

**Comment by jzuhone** [comment]
I'm having the same issue on macOS.

**Comment by xEtarusx** [comment]
Pressing the "Check for updates" button turns the butten into a "Update" button which only redirects me to the github release page.
There is an option in the settings called "Automatic Updates: Enable automatic installation of updates when they become available."
Is this option currently broken?

**Comment by jzuhone** [comment]
The lack of responsiveness on this issue is one of the reasons I switched back to iTerm (sadly).

**Comment by gitgt** [comment]
I'm new user, but Check for updates worked in portable Windows tabby to update from 1.0.187 to 1.0.188. 
Please retest.

**Comment by xEtarusx** [comment]
Could it be a problem with admin rights. On my system the C: drive is only accessible for admin users and my default user doesn't have admin rights. 
The installation via the msi installer failed due to missing admin rights. Running the installer as admin fixed my problems.
I'll try the update button next time an update is available after I run the program as admin.

**Comment by gitgt** [comment]
@xEtarusx Makes sense. You may use portable version where user has rights. Seems like "NotABug".
