### ISSUE TITLE
Powershell Core still doesn't launch launch on Windows

### ISSUE THREAD

**Issue by mikemaccana** [Eugeny/terminus#382]
DevTools output. Terminus `1.0.0-alpha48`: 

    ERROR Error: Uncaught (in promise): Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: File not found: 
    Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: File not found: 
        at callFunction (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\electron.asar\browser\rpc-server.js:257:11)
        at EventEmitter.<anonymous> (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\electron.asar\browser\rpc-server.js:357:5)
        at emitMany (events.js:147:13)
        at EventEmitter.emit (events.js:224:7)
        at WebContents.<anonymous> (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\electron.asar\browser\api\web-contents.js:295:13)
        at emitTwo (events.js:126:13)
        at WebContents.emit (events.js:214:7)
    Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: File not found: 
    Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: File not found: 
        at callFunction (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\electron.asar\browser\rpc-server.js:257:11)
        at EventEmitter.<anonymous> (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\electron.asar\browser\rpc-server.js:357:5)
        at emitMany (events.js:147:13)
        at EventEmitter.emit (events.js:224:7)
        at WebContents.<anonymous> (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\electron.asar\browser\api\web-contents.js:295:13)
        at emitTwo (events.js:126:13)
        at WebContents.emit (events.js:214:7)
        at Object.exception (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\electron.asar\renderer\api\remote.js:209:30)
        at metaToValue (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\electron.asar\renderer\api\remote.js:213:28)
        at Object.remoteMemberFunction (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\electron.asar\renderer\api\remote.js:113:16)
        at new u (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:78:2259)
        at C.addSession (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:78:4155)
        at l.<anonymous> (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:85:1975)
        at Generator.next (<anonymous>)
        at C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:85:927
        at new ZoneAwarePromise (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:891:29)
        at i (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:85:704)
        at callFunction (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\electron.asar\browser\rpc-server.js:257:11)
        at EventEmitter.<anonymous> (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\electron.asar\browser\rpc-server.js:357:5)
        at emitMany (events.js:147:13)
        at EventEmitter.emit (events.js:224:7)
        at WebContents.<anonymous> (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\electron.asar\browser\api\web-contents.js:295:13)
        at emitTwo (events.js:126:13)
        at WebContents.emit (events.js:214:7)
    Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: File not found: 
    Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: File not found: 
        at callFunction (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\electron.asar\browser\rpc-server.js:257:11)
        at EventEmitter.<anonymous> (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\electron.asar\browser\rpc-server.js:357:5)
        at emitMany (events.js:147:13)
        at EventEmitter.emit (events.js:224:7)
        at WebContents.<anonymous> (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\electron.asar\browser\api\web-contents.js:295:13)
        at emitTwo (events.js:126:13)
        at WebContents.emit (events.js:214:7)
        at Object.exception (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\electron.asar\renderer\api\remote.js:209:30)
        at metaToValue (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\electron.asar\renderer\api\remote.js:213:28)
        at Object.remoteMemberFunction (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\electron.asar\renderer\api\remote.js:113:16)
        at new u (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:78:2259)
        at C.addSession (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:78:4155)
        at l.<anonymous> (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:85:1975)
        at Generator.next (<anonymous>)
        at C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:85:927
        at new ZoneAwarePromise (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:891:29)
        at i (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:85:704)
        at resolvePromise (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:814:31)
        at new ZoneAwarePromise (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:894:17)
        at i (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:85:704)
        at SafeSubscriber.resize$.pipe.subscribe.V [as _next] (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:85:1900)
        at SafeSubscriber.__tryOrUnsub (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:263:16)
        at SafeSubscriber.next (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:201:22)
        at Subscriber._next (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:139:26)
        at Subscriber.next (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:103:18)
        at TapSubscriber._next (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\rxjs\internal\operators\tap.js:109:26)
        at TapSubscriber.Subscriber.next (C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:103:18)
    defaultErrorLogger @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1682
    ErrorHandler.handleError @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1731
    next @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4811
    schedulerFn @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:3796
    SafeSubscriber.__tryOrUnsub @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:263
    SafeSubscriber.next @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:201
    Subscriber._next @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:139
    Subscriber.next @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:103
    Subject.next @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\rxjs\internal\Subject.js:63
    EventEmitter.emit @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:3788
    (anonymous) @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4168
    ZoneDelegate.invoke @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:388
    Zone.run @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:138
    NgZone.runOutsideAngular @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4105
    onHandleError @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4168
    ZoneDelegate.handleError @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:392
    Zone.runGuarded @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:154
    _loop_1 @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:677
    api.microtaskDrainDone @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:686
    drainMicroTaskQueue @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:602
    ZoneTask.invokeTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:500
    ZoneTask.invoke @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:485
    timer @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:2054
    setTimeout (async)
    scheduleTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:2075
    ZoneDelegate.scheduleTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:407
    onScheduleTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:297
    ZoneDelegate.scheduleTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:401
    Zone.scheduleTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:232
    Zone.scheduleMacroTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:255
    scheduleMacroTaskWithCurrentZone @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:1114
    (anonymous) @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:2090
    proto.(anonymous function) @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:1394
    t._htermExports.r.PubSub.publish @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:428
    t._htermExports.r.ScrollPort.resize @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:428
    V.scrollPort_.resize @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:85
    t._htermExports.r.ScrollPort.syncCharacterSize @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:428
    t._htermExports.r.ScrollPort.setFontFamily @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:428
    t._htermExports.r.Terminal.syncFontFamily @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:428
    font-family @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:428
    t._htermExports.A.PreferenceManager.notifyChange_ @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:428
    t._htermExports.A.PreferenceManager.notifyAll @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:428
    (anonymous) @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:428
    ZoneDelegate.invokeTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:421
    onInvokeTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4137
    ZoneDelegate.invokeTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:420
    Zone.runTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:188
    ZoneTask.invokeTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:496
    ZoneTask.invoke @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:485
    timer @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:2054
    setTimeout (async)
    scheduleTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:2075
    ZoneDelegate.scheduleTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:407
    onScheduleTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:297
    ZoneDelegate.scheduleTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:401
    Zone.scheduleTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:232
    Zone.scheduleMacroTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:255
    scheduleMacroTaskWithCurrentZone @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:1114
    (anonymous) @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:2090
    proto.(anonymous function) @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:1394
    (anonymous) @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:428
    ZoneDelegate.invokeTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:421
    onInvokeTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4137
    ZoneDelegate.invokeTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:420
    Zone.runTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:188
    ZoneTask.invokeTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:496
    ZoneTask.invoke @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:485
    timer @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:2054
    setTimeout (async)
    scheduleTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:2075
    ZoneDelegate.scheduleTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:407
    onScheduleTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:297
    ZoneDelegate.scheduleTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:401
    Zone.scheduleTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:232
    Zone.scheduleMacroTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:255
    scheduleMacroTaskWithCurrentZone @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:1114
    (anonymous) @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:2090
    proto.(anonymous function) @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:1394
    t._htermExports.A.Storage.Memory.getItems @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:428
    t._htermExports.A.PreferenceManager.readStorage @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:428
    t._htermExports.r.Terminal.setProfile @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:428
    t._htermExports.r.Terminal @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:428
    ngOnInit @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\builtin-plugins\terminus-terminal\dist\index.js:85
    checkAndUpdateDirectiveInline @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:10181
    checkAndUpdateNodeInline @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11447
    checkAndUpdateNode @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11409
    prodCheckAndUpdateNode @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11953
    (anonymous) @ l_Host.ngfactory.js:11
    updateDirectives @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11739
    checkAndUpdateView @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11391
    callViewAction @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11632
    execEmbeddedViewsAction @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11595
    checkAndUpdateView @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11392
    callViewAction @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11632
    execEmbeddedViewsAction @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11595
    checkAndUpdateView @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11392
    callViewAction @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11632
    execComponentViewsAction @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11574
    checkAndUpdateView @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11397
    callViewAction @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11632
    execEmbeddedViewsAction @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11595
    checkAndUpdateView @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11392
    callViewAction @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11632
    execComponentViewsAction @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11574
    checkAndUpdateView @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:11397
    ViewRef_.detectChanges @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:9776
    (anonymous) @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:5170
    ApplicationRef.tick @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:5170
    (anonymous) @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:5013
    ZoneDelegate.invoke @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:388
    onInvoke @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4146
    ZoneDelegate.invoke @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:387
    Zone.run @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:138
    NgZone.run @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4002
    next @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:5013
    schedulerFn @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:3796
    SafeSubscriber.__tryOrUnsub @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:263
    SafeSubscriber.next @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:201
    Subscriber._next @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:139
    Subscriber.next @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:103
    Subject.next @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\rxjs\internal\Subject.js:63
    EventEmitter.emit @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:3788
    checkStable @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4115
    onLeave @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4182
    onInvokeTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4140
    ZoneDelegate.invokeTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:420
    Zone.runTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:188
    ZoneTask.invokeTask @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:496
    ZoneTask.invoke @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:485
    timer @ C:\Users\mike\AppData\Local\terminus\app-1.0.0-alpha48\resources\app.asar\node_modules\zone.js\dist\zone.js:2054
    runCallback @ timers.js:789
    tryOnImmediate @ timers.js:751
    processImmediate @ timers.js:722

**Comment by mikemaccana** [comment]
Thanks Eugeny! Really looking forward to trying these when the next release release comes out!
