### ISSUE TITLE
Have issue with sz/rz 

### ISSUE THREAD

**Issue by meteorjim** [Eugeny/terminus#3914]
Version: 1.0.139
Platform: win32 10.0.19043
Plugins: quick-cmds, relaxed-theme, theme-windows10

Hi~ I've seen that terminus support rzsz, but I still can not use this feature, should I config Zmodem in somewhere or install something on my server? [ rz sz in xshell works fine ]

(pytest) [iotest@localhost ~]$ sz --version
sz (lrzsz) 0.12.20

![image](https://user-images.githubusercontent.com/10251260/119914153-2f9ed180-bf92-11eb-9bce-e9170fc4863f.png)

Here is the error log I found in devTools
```
C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:6479 ERROR Error: Uncaught (in promise): Error: Can not find Squirrel
Error: Can not find Squirrel
    at AutoUpdater.method [as checkForUpdates] (electron/js2c/browser_init.js:17:1405)
    at handler (C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@electron\remote\dist\src\main\server.js:454:64)
    at IpcMainImpl.<anonymous> (C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@electron\remote\dist\src\main\server.js:313:27)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10351)
    at Object.emit (events.js:315:20)
    at Object.apply [as emit] (domain.js:467:12)
    at Object.n.emit (C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@sentry\electron\dist\main\integrations\electron.js:66:25)
    at resolvePromise (C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1255:35)
    at resolvePromise (C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1209:21)
    at C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1321:21
    at ZoneDelegate.invokeTask (C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:434:35)
    at Object.onInvokeTask (C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29190:37)
    at ZoneDelegate.invokeTask (C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:433:64)
    at Zone.runTask (C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:205:51)
    at drainMicroTaskQueue (C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:620:39)
defaultErrorLogger @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:6479
ErrorHandler.handleError @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:6527
next @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29814
schedulerFn @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:26572
SafeSubscriber.__tryOrUnsub @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:205
SafeSubscriber.next @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:143
Subscriber._next @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:89
Subscriber.next @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66
Subject.next @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subject.js:60
EventEmitter_.emit @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:26562
(anonymous) @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29229
ZoneDelegate.invoke @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:400
Zone.run @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:160
NgZone.runOutsideAngular @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29131
onHandleError @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29229
ZoneDelegate.handleError @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:404
Zone.runGuarded @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:174
_loop_2 @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1113
api.microtaskDrainDone @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1125
drainMicroTaskQueue @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:627
Promise.then (async)
scheduleMicroTask @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:603
ZoneDelegate.scheduleTask @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:424
onScheduleTask @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:311
ZoneDelegate.scheduleTask @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:414
Zone.scheduleTask @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:248
Zone.scheduleMicroTask @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:268
scheduleResolveOrReject @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1308
resolvePromise @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1246
(anonymous) @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1162
onError @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:36243
apply @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:4784
(anonymous) @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:5169
(anonymous) @ C:\Users\jim\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-core\dist\index.js:5151
emit @ events.js:327
onMessage @ electron/js2c/renderer_init.js:93
```

**Comment by ydcool** [comment]
I have the same issue
