### ISSUE TITLE
Can't open any terminal

### ISSUE THREAD

**Issue by Hzpa** [Eugeny/terminus#3978]
Version: 1.0.139
Platform: win32 10.0.18363
Plugins: quick-cmds

![image](https://user-images.githubusercontent.com/37492919/121505561-83d79600-ca15-11eb-9a00-9d529a7681c6.png)
![image](https://user-images.githubusercontent.com/37492919/121505595-8c2fd100-ca15-11eb-806d-e4715835750c.png)

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by Hzpa** [comment]
D:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:6479 ERROR Error: Uncaught (in promise): Error: Can not find Squirrel
Error: Can not find Squirrel
    at AutoUpdater.method [as checkForUpdates] (electron/js2c/browser_init.js:17:1405)
    at handler (D:\Program Files\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@electron\remote\dist\src\main\server.js:454:64)
    at IpcMainImpl.<anonymous> (D:\Program Files\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@electron\remote\dist\src\main\server.js:313:27)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10351)
    at Object.emit (events.js:315:20)
    at Object.apply [as emit] (domain.js:467:12)
    at Object.n.emit (D:\Program Files\Terminus\resources\app.asar\dist\webpack:\terminus\node_modules\@sentry\electron\dist\main\integrations\electron.js:66:25)
    at resolvePromise (D:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1255:35)
    at resolvePromise (D:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1209:21)
    at D:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1321:21
    at ZoneDelegate.invokeTask (D:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:434:35)
    at Object.onInvokeTask (D:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:29190:37)
    at ZoneDelegate.invokeTask (D:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:433:64)
    at Zone.runTask (D:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:205:51)
    at drainMicroTaskQueue (D:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:620:39)
