### ISSUE TITLE
Cannot build latest version in windows

### ISSUE THREAD

**Issue by Domain** [Eugeny/terminus#401]
PS C:\git\terminus> node .\scripts\build-native.js
Rebuilding font-manager
Rebuilding electron-vibrancy
Rebuilding wincredmgr
(node:2084) UnhandledPromiseRejectionWarning: Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.8.0 | win32 | x64
gyp info spawn C:\Users\Domain-Work\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Git\\terminus\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\git\\terminus\\terminus-ssh\\node_modules\\wincredmgr\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Git\\terminus\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Domain-Work\\.electron-gyp\\.node-gyp\\iojs-3.0.0-beta.5\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Domain-Work\\.electron-gyp\\.node-gyp\\iojs-3.0.0-beta.5',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Git\\terminus\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Domain-Work\\.electron-gyp\\.node-gyp\\iojs-3.0.0-beta.5\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\git\\terminus\\terminus-ssh\\node_modules\\wincredmgr',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\git\\terminus\\terminus-ssh\\node_modules\\wincredmgr\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
  wincredmgr.cpp
  win_delay_load_hook.cc
c:\git\terminus\terminus-ssh\node_modules\wincredmgr\wincredmgr.cpp(26): warning C4996: 'v8::String::Utf8Value::Utf8Value': ������Ϊ�ѷ�� [C:\git\terminus\terminus-ssh\node_modules\wincredmgr\build\wincredmgr.vcxproj]
  c:\users\domain-work\.electron-gyp\.node-gyp\iojs-3.0.0-beta.5\deps\v8\include\v8.h(2819): note: �μ���v8::String::Utf8Value::Utf8Value��������
c:\git\terminus\terminus-ssh\node_modules\wincredmgr\wincredmgr.cpp(27): warning C4996: 'v8::String::Utf8Value::Utf8Value': ������Ϊ�ѷ�� [C:\git\terminus\terminus-ssh\node_modules\wincredmgr\build\wincredmgr.vcxproj]
  c:\users\domain-work\.electron-gyp\.node-gyp\iojs-3.0.0-beta.5\deps\v8\include\v8.h(2819): note: �μ���v8::String::Utf8Value::Utf8Value��������
c:\git\terminus\terminus-ssh\node_modules\wincredmgr\wincredmgr.cpp(28): warning C4996: 'v8::String::Utf8Value::Utf8Value': ������Ϊ�ѷ�� [C:\git\terminus\terminus-ssh\node_modules\wincredmgr\build\wincredmgr.vcxproj]
  c:\users\domain-work\.electron-gyp\.node-gyp\iojs-3.0.0-beta.5\deps\v8\include\v8.h(2819): note: �μ���v8::String::Utf8Value::Utf8Value��������
c:\git\terminus\terminus-ssh\node_modules\wincredmgr\wincredmgr.cpp(62): warning C4996: 'v8::String::Utf8Value::Utf8Value': ������Ϊ�ѷ�� [C:\git\terminus\terminus-ssh\node_modules\wincredmgr\build\wincredmgr.vcxproj]
  c:\users\domain-work\.electron-gyp\.node-gyp\iojs-3.0.0-beta.5\deps\v8\include\v8.h(2819): note: �μ���v8::String::Utf8Value::Utf8Value��������
c:\git\terminus\terminus-ssh\node_modules\wincredmgr\wincredmgr.cpp(111): warning C4996: 'v8::String::Utf8Value::Utf8Value': ������Ϊ�ѷ�� [C:\git\terminus\terminus-ssh\node_modules\wincredmgr\build\wincredmgr.vcxproj]
  c:\users\domain-work\.electron-gyp\.node-gyp\iojs-3.0.0-beta.5\deps\v8\include\v8.h(2819): note: �μ���v8::String::Utf8Value::Utf8Value��������
C:\Users\Domain-Work\.electron-gyp\.node-gyp\iojs-3.0.0-beta.5\x64\iojs.lib : fatal error LNK1106: �ļ���Ч���������: �޷����ҵ� 0x2B4286 [C:\git\terminus\terminus-ssh\node_modules\wincredmgr\build\wincredmgr.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Git\terminus\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Windows_NT 10.0.17746
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Git\\terminus\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=3.0.0-beta.5" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd C:\git\terminus\terminus-ssh\node_modules\wincredmgr
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\git\terminus\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (C:\git\terminus\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.error (C:\git\terminus\node_modules\rxjs\Subscriber.js:201:26)
    at Subscriber._error (C:\git\terminus\node_modules\rxjs\Subscriber.js:132:26)
    at Subscriber.error (C:\git\terminus\node_modules\rxjs\Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (C:\git\terminus\node_modules\rxjs\Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (C:\git\terminus\node_modules\rxjs\Subscriber.js:106:18)
    at SafeSubscriber._next (C:\git\terminus\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrSetError (C:\git\terminus\node_modules\rxjs\Subscriber.js:251:16)
    at SafeSubscriber.next (C:\git\terminus\node_modules\rxjs\Subscriber.js:191:27)
(node:2084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2084) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2084) UnhandledPromiseRejectionWarning: Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.8.0 | win32 | x64
gyp info spawn C:\Users\Domain-Work\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Git\\terminus\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\git\\terminus\\terminus-terminal\\node_modules\\font-manager\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Git\\terminus\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Domain-Work\\.electron-gyp\\.node-gyp\\iojs-3.0.0-beta.5\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Domain-Work\\.electron-gyp\\.node-gyp\\iojs-3.0.0-beta.5',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Git\\terminus\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Domain-Work\\.electron-gyp\\.node-gyp\\iojs-3.0.0-beta.5\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\git\\terminus\\terminus-terminal\\node_modules\\font-manager',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\git\\terminus\\terminus-terminal\\node_modules\\font-manager\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
  FontManager.cc
  FontManagerWindows.cc
  win_delay_load_hook.cc
C:\Users\Domain-Work\.electron-gyp\.node-gyp\iojs-3.0.0-beta.5\x64\iojs.lib : fatal error LNK1106: �ļ���Ч���������: �޷����ҵ� 0x2B4286 [C:\git\terminus\terminus-terminal\node_modules\font-manager\build\fontmanager.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Git\terminus\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Windows_NT 10.0.17746
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Git\\terminus\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=3.0.0-beta.5" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd C:\git\terminus\terminus-terminal\node_modules\font-manager
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\git\terminus\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (C:\git\terminus\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.error (C:\git\terminus\node_modules\rxjs\Subscriber.js:201:26)
    at Subscriber._error (C:\git\terminus\node_modules\rxjs\Subscriber.js:132:26)
    at Subscriber.error (C:\git\terminus\node_modules\rxjs\Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (C:\git\terminus\node_modules\rxjs\Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (C:\git\terminus\node_modules\rxjs\Subscriber.js:106:18)
    at SafeSubscriber._next (C:\git\terminus\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrSetError (C:\git\terminus\node_modules\rxjs\Subscriber.js:251:16)
    at SafeSubscriber.next (C:\git\terminus\node_modules\rxjs\Subscriber.js:191:27)
(node:2084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2084) UnhandledPromiseRejectionWarning: Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.8.0 | win32 | x64
gyp info spawn C:\Users\Domain-Work\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Git\\terminus\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\git\\terminus\\app\\node_modules\\electron-vibrancy\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Git\\terminus\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Domain-Work\\.electron-gyp\\.node-gyp\\iojs-3.0.0-beta.5\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Domain-Work\\.electron-gyp\\.node-gyp\\iojs-3.0.0-beta.5',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Git\\terminus\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Domain-Work\\.electron-gyp\\.node-gyp\\iojs-3.0.0-beta.5\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\git\\terminus\\app\\node_modules\\electron-vibrancy',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\git\\terminus\\app\\node_modules\\electron-vibrancy\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
  Vibrancy.cc
  vibrancy_win.cc
  Init.cc
  win_delay_load_hook.cc
c:\git\terminus\app\node_modules\electron-vibrancy\src\vibrancy_win.cc(57): warning C4996: 'GetVersionExA': ������Ϊ�ѷ�� [C:\git\terminus\app\node_modules\electron-vibrancy\build\Vibrancy.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17134.0\um\sysinfoapi.h(378): note: �μ���GetVersionExA��������
c:\git\terminus\app\node_modules\electron-vibrancy\src\vibrancy_win.cc(112): warning C4312: ������ǿ��ת����: �ӡ�uint32_t��ת��������ġ�HWND�� [C:\git\terminus\app\node_modules\electron-vibrancy\build\Vibrancy.vcxproj]
c:\git\terminus\app\node_modules\electron-vibrancy\src\vibrancy_win.cc(120): warning C4312: ������ǿ��ת����: �ӡ�uint32_t��ת��������ġ�HWND�� [C:\git\terminus\app\node_modules\electron-vibrancy\build\Vibrancy.vcxproj]
C:\Users\Domain-Work\.electron-gyp\.node-gyp\iojs-3.0.0-beta.5\x64\iojs.lib : fatal error LNK1106: �ļ���Ч���������: �޷����ҵ� 0x2B4286 [C:\git\terminus\app\node_modules\electron-vibrancy\build\Vibrancy.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Git\terminus\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Windows_NT 10.0.17746
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Git\\terminus\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=3.0.0-beta.5" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd C:\git\terminus\app\node_modules\electron-vibrancy
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\git\terminus\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (C:\git\terminus\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.error (C:\git\terminus\node_modules\rxjs\Subscriber.js:201:26)
    at Subscriber._error (C:\git\terminus\node_modules\rxjs\Subscriber.js:132:26)
    at Subscriber.error (C:\git\terminus\node_modules\rxjs\Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (C:\git\terminus\node_modules\rxjs\Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (C:\git\terminus\node_modules\rxjs\Subscriber.js:106:18)
    at SafeSubscriber._next (C:\git\terminus\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrSetError (C:\git\terminus\node_modules\rxjs\Subscriber.js:251:16)
    at SafeSubscriber.next (C:\git\terminus\node_modules\rxjs\Subscriber.js:191:27)
(node:2084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
PS C:\git\terminus>

And how can I get the correct character in error message?

**Comment by Domain** [comment]
For those who has the same display problem in powershell, use the following command:

`$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding`

**Comment by Domain** [comment]
Looks like my network problem.
