### ISSUE TITLE
Unable to run 1.0.0-alpha.61 on Windows 10

### ISSUE THREAD

**Issue by bjohnso5** [Eugeny/terminus#474]
When I run `terminus.exe --debug`, I get the following stack trace in the devtools console:
```
Error: Cannot find module 'rxjs-compat/add/operator/bufferTime'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (C:\Users\bjohnson\AppData\Local\terminus\app-1.0.0-alpha61\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\bjohnson\AppData\Local\terminus\app-1.0.0-alpha61\resources\app.asar\node_modules\rxjs\add\operator\bufferTime.js:3:1)
    at Object.<anonymous> (C:\Users\bjohnson\AppData\Local\terminus\app-1.0.0-alpha61\resources\app.asar\node_modules\rxjs\add\operator\bufferTime.js:5:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
```

Does Terminus require a specific host version of Node to be installed? I have the same error with 1.0.0-alpha.59 as well.

**Comment by Eugeny** [comment]
Does this still happen with a fresh build?

**Comment by bjohnso5** [comment]
This issue is specific to my work machine, I'll have to remote in and give the latest a try to know for sure. I'll reply back to this thread with the results of that test.

**Comment by bjohnso5** [comment]
Yes, with Alpha 65, I see the exact same behaviour:

Error: Cannot find module 'rxjs-compat/add/operator/bufferTime'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584)
    at Function.Module._resolveFilename (C:\Users\bjohnson\Ap…-search-paths.js:43)
    at Function.Module._load (internal/modules/cjs/loader.js:510)
    at Module.require (internal/modules/cjs/loader.js:640)
    at require (internal/modules/cjs/helpers.js:20)
    at Object.<anonymous> (C:\Users\bjohnson\Ap…tor\bufferTime.js:3)
    at Object.<anonymous> (C:\Users\bjohnson\Ap…tor\bufferTime.js:5)
    at Module._compile (internal/modules/cjs/loader.js:693)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704)
    at Module.load (internal/modules/cjs/loader.js:602)

I have a feeling it's related to the real time protection that our corporate antivirus software uses, it's likely preventing the .asar file from being decompressed properly or something. I don't have this issue at home. I'm just going to close this, as I doubt you'll be able to get very far with a solution.

Cheers.

**Comment by Eugeny** [comment]
I would also try removing any installed plugins
