### ISSUE TITLE
Portable version doesn't support plugins or persistence

### ISSUE THREAD

**Issue by sytelus** [Eugeny/terminus#478]
I installed all available plugin and got prompt to restart the app on Windows 10. During restart I got error message:

![image](https://user-images.githubusercontent.com/2096835/47599117-f88c5d80-d95b-11e8-8dc4-09f3baed4e7e.png)

**Text form for searchability:**

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> (C:\Users\shitals\AppData\Local\Temp\nsqBFFB.tmp\app\resources\electron.asar\browser\init.js:121:9)
    at Object.<anonymous> (C:\Users\shitals\AppData\Local\Temp\nsqBFFB.tmp\app\resources\electron.asar\browser\init.js:191:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)
    at startup (internal/bootstrap/node.js:241:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)

[OK]
```

Basically Terminus has become unusable. It would be good to check the offending plugin and disable it.

**config.yaml**
From related issue https://github.com/Eugeny/terminus/issues/476, I got [config.yaml](https://github.com/Eugeny/terminus/wiki/Config-file)from `%APPDATA%/Terminus`.
```
ssh: {}
hotkeys: {}
terminal:
  workingDirectory: 'D:\GitHubSrc\pytorch-CycleGAN-and-pix2pix'
  rightClick: menu
appearance:
  theme: Standard
pluginBlacklist: []
```

**Comment by indice** [comment]
+1 
Same problem

![image](https://user-images.githubusercontent.com/4303767/52879923-d879e780-3160-11e9-82c0-054653af481f.png)
