### ISSUE TITLE
No shell

### ISSUE THREAD

**Issue by SplittyDev** [Eugeny/terminus#548]
Hey, I wanted to give terminus a try but can't open a new terminal tab. The shell list is empty for me;
I tried to add zsh manually but couldn't figure out how to properly add it to the configuration file.

**Comment by Eugeny** [comment]
Could you please check the debug console for errors? https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by SplittyDev** [comment]
Apparently, terminus doesn't have sufficient permissions.

```
RROR Error: Uncaught (in promise): Error: EACCES: permission denied, open '/etc/shells'
Error: EACCES: permission denied, open '/etc/shells'
    at resolvePromise (/snap/terminus/x1/resources/app.asar/node_modules/zone.js/dist/zone.js:814)
    at /snap/terminus/x1/resources/app.asar/node_modules/zone.js/dist/zone.js:724
    at rejected (/snap/terminus/x1/resources/builtin-plugins/terminus-terminal/dist/index.js:817)
    at ZoneDelegate.invoke (/snap/terminus/x1/resources/app.asar/node_modules/zone.js/dist/zone.js:388)
    at Object.onInvoke (ng_zone.ts:273)
    at ZoneDelegate.invoke (/snap/terminus/x1/resources/app.asar/node_modules/zone.js/dist/zone.js:387)
    at Zone.run (/snap/terminus/x1/resources/app.asar/node_modules/zone.js/dist/zone.js:138)
    at /snap/terminus/x1/resources/app.asar/node_modules/zone.js/dist/zone.js:872
    at ZoneDelegate.invokeTask (/snap/terminus/x1/resources/app.asar/node_modules/zone.js/dist/zone.js:421)
    at Object.onInvokeTask (ng_zone.ts:262)
```

I just tried running with sudo, but then I get the following:
```
splitty in ~ λ sudo terminus                                    
mkdir: cannot create directory '/run/user/0': Permission denied
ln: failed to create symbolic link '/root/snap/terminus/x1/snap/terminus/x1/Documents': No such file or directory
ln: failed to create symbolic link '/root/snap/terminus/x1/snap/terminus/x1/Desktop': No such file or directory
ln: failed to create symbolic link '/root/snap/terminus/x1/snap/terminus/x1/Downloads': No such file or directory
ln: failed to create symbolic link '/root/snap/terminus/x1/snap/terminus/x1/Music': No such file or directory
ln: failed to create symbolic link '/root/snap/terminus/x1/snap/terminus/x1/Pictures': No such file or directory
ln: failed to create symbolic link '/root/snap/terminus/x1/snap/terminus/x1/Videos': No such file or directory
ln: failed to create symbolic link '/root/snap/terminus/x1/snap/terminus/x1/Templates': No such file or directory
No protocol specified
```

I'm sure the second error has to do with snaps though, so that's probably not specific to terminus.

**Comment by SplittyDev** [comment]
I just removed the snap and reinstalled it with the `--classic` flag, which fixed the issue described above. However, I still can't open a new terminal tab. All my shells are shown now, but as soon as I open a terminal tab it instantly closes.

Here's the relevant log:
```
[terminal] Starting shell /bin/zsh {id: "/bin/zsh", name: "/bin/zsh", command: "/bin/zsh", args: Array(1)}
log.service.ts:43 [terminal] Using session options: {command: "/bin/zsh", args: Array(1), cwd: null, env: {…}, pauseAfterExit: undefined}
hterm.ts:55 mode 1
htermFrontend.ts:166 hterm resize
terminalTab.component.ts:281 Resizing to 91x33
htermFrontend.ts:166 hterm resize
terminalTab.component.ts:281 Resizing to 91x33
htermFrontend.ts:166 hterm resize
terminalTab.component.ts:281 Resizing to 91x33
sessions.service.ts:143 session close
sessions.service.ts:134 session exit
```

**Comment by SplittyDev** [comment]
After playing around with the settings, this problem doesn't seem to be affecting all shells.

The following shells work for me:
- /bin/bash
- /bin/rbash

The following shells don't work:
- /bin/sh
- /bin/dash
- /bin/zsh, /usr/bin/zsh

So it really only works for bash, all other shells fail for unknown reasons.

**Comment by Eugeny** [comment]
Could you please compare this behaviour with the `deb` / standalone `tgz` builds?

**Comment by SplittyDev** [comment]
Using the deb package, everything works as expected.

I found another issue with the snap package while testing the deb package:
Plugins aren't fetched from the plugin repository in the snap version.

I was surprised when I saw the section for downloadable plugins, in the snap version that just isn't there.

**Comment by Bevisy** [comment]
+1 use snap package and can't add new terminal

**Comment by mintyPT** [comment]
I'm currently having issues with zsh (default shell). When I click "New terminal", it briefly opens a new tab before closing it right away.

> **If you want a thing done well, do it yourself.**
> Napoleon Bonaparte

**Comment by quantabox** [comment]
I have issues opening a Cygwin - Bash or Cygwin - Fish shells on windows
```
Failed to load resource: net::ERR_FILE_NOT_FOUND
C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4034 ERROR Error: Error launching WinPTY agent: ConnectNamedPipe failed: Windows error 232
    at new WindowsPtyAgent (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:77:36)
    at new WindowsTerminal (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:49:24)
    at spawn (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\node-pty\lib\index.js:28:12)
    at Object.mod.spawn (webpack-internal:///2058:9:20)
    at Session.start (webpack-internal:///5102:448:39)
    at SessionsService.addSession (webpack-internal:///5102:651:17)
    at TerminalTabComponent.initializeSession (webpack-internal:///5102:2409:23)
    at SafeSubscriber.eval [as _next] (webpack-internal:///5102:2404:18)
    at SafeSubscriber.__tryOrUnsub (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:143:22)
    at Subscriber._next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\operators\throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at TakeSubscriber._next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\operators\take.js:54:30)
    at TakeSubscriber.Subscriber.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Subject.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subject.js:60:25)
    at TerminalTabComponent.eval (webpack-internal:///5102:2095:32)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///5102:68:71)
    at new ZoneAwarePromise (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:915:33)
    at __awaiter (webpack-internal:///5102:64:12)
    at SafeSubscriber.eval [as _next] (webpack-internal:///5102:2093:93)
    at SafeSubscriber.__tryOrUnsub (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:143:22)
    at Subscriber._next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\operators\throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at TakeSubscriber._next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\operators\take.js:54:30)
    at TakeSubscriber.Subscriber.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
    at ReplaySubject.Subject.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subject.js:60:25)
    at ReplaySubject.nextInfiniteTimeWindow (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\ReplaySubject.js:48:31)
```

**Comment by r0b3rt85** [comment]
> I have issues opening a Cygwin - Bash or Cygwin - Fish shells on windows
> 
> ```
> Failed to load resource: net::ERR_FILE_NOT_FOUND
> C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4034 ERROR Error: Error launching WinPTY agent: ConnectNamedPipe failed: Windows error 232
>     at new WindowsPtyAgent (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:77:36)
>     at new WindowsTerminal (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:49:24)
>     at spawn (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\node-pty\lib\index.js:28:12)
>     at Object.mod.spawn (webpack-internal:///2058:9:20)
>     at Session.start (webpack-internal:///5102:448:39)
>     at SessionsService.addSession (webpack-internal:///5102:651:17)
>     at TerminalTabComponent.initializeSession (webpack-internal:///5102:2409:23)
>     at SafeSubscriber.eval [as _next] (webpack-internal:///5102:2404:18)
>     at SafeSubscriber.__tryOrUnsub (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:205:16)
>     at SafeSubscriber.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:143:22)
>     at Subscriber._next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:89:26)
>     at Subscriber.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
>     at ThrowIfEmptySubscriber._next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\operators\throwIfEmpty.js:44:26)
>     at ThrowIfEmptySubscriber.Subscriber.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
>     at TakeSubscriber._next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\operators\take.js:54:30)
>     at TakeSubscriber.Subscriber.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
>     at Subject.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subject.js:60:25)
>     at TerminalTabComponent.eval (webpack-internal:///5102:2095:32)
>     at Generator.next (<anonymous>)
>     at eval (webpack-internal:///5102:68:71)
>     at new ZoneAwarePromise (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:915:33)
>     at __awaiter (webpack-internal:///5102:64:12)
>     at SafeSubscriber.eval [as _next] (webpack-internal:///5102:2093:93)
>     at SafeSubscriber.__tryOrUnsub (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:205:16)
>     at SafeSubscriber.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:143:22)
>     at Subscriber._next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:89:26)
>     at Subscriber.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
>     at ThrowIfEmptySubscriber._next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\operators\throwIfEmpty.js:44:26)
>     at ThrowIfEmptySubscriber.Subscriber.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
>     at TakeSubscriber._next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\operators\take.js:54:30)
>     at TakeSubscriber.Subscriber.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:66:18)
>     at ReplaySubject.Subject.next (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\Subject.js:60:25)
>     at ReplaySubject.nextInfiniteTimeWindow (C:\Users\<>\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\rxjs\internal\ReplaySubject.js:48:31)
> ```

I have exactly the same issue and the terminal is now unusable.

![image](https://user-images.githubusercontent.com/20833072/81501962-f5a15580-92d2-11ea-8f20-3563a2a50bea.png)
