### ISSUE TITLE
build failure in git?

### ISSUE THREAD

**Issue by SolarAquarion** [Eugeny/terminus#550]
Unhandled rejection Error: Application entry file "dist/main.js" in the "/home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
    at /home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:33:11
    at Generator.next (<anonymous>)
    at /home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/fs-extra-p/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:161:5)
From previous event:
    at checkFileInArchive (/home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/app-builder-lib/out/asar/asarFileChecker.js:78:17)
    at /home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/app-builder-lib/src/platformPackager.ts:395:13
    at Generator.next (<anonymous>)
From previous event:
    at LinuxPackager.checkFileInPackage (/home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/app-builder-lib/src/platformPackager.ts:392:110)
    at /home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/app-builder-lib/src/platformPackager.ts:444:16
    at Generator.next (<anonymous>)
    at /home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/fs-extra-p/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:161:5)
From previous event:
    at LinuxPackager.sanityCheckPackage (/home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/app-builder-lib/src/platformPackager.ts:431:70)
    at /home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/app-builder-lib/src/platformPackager.ts:235:16
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at LinuxPackager.doPack (/home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/app-builder-lib/src/platformPackager.ts:166:165)
    at /home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/app-builder-lib/src/platformPackager.ts:112:16
    at Generator.next (<anonymous>)
From previous event:
    at LinuxPackager.pack (/home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/app-builder-lib/src/platformPackager.ts:110:95)
    at /home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/fs-extra-p/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:161:5)
From previous event:
    at Packager.doBuild (/home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/app-builder-lib/src/packager.ts:344:39)
    at /home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/app-builder-lib/src/packager.ts:314:57
    at Generator.next (<anonymous>)
    at /home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/fs-extra-p/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/fs-extra-p/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.args [as oncomplete] (fs.js:147:20)
From previous event:
    at Packager._build (/home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/app-builder-lib/src/packager.ts:285:133)
    at /home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at Packager.build (/home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/app-builder-lib/src/index.ts:58:28)
    at build (/home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/node_modules/electron-builder/src/builder.ts:227:10)
    at Object.<anonymous> (/home/solaraquarion/pkgbuild/terminus-terminal-git/src/Terminus/scripts/build-linux.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by Eugeny** [comment]
Have you followed the [build instructions](https://github.com/Eugeny/terminus/blob/master/HACKING.md)? `dist/main.js` is produced by `npm run build`

**Comment by SolarAquarion** [comment]
It failed during the building linux-unpacked thing

**Comment by Eugeny** [comment]
I see that. Did the `npm run build` succeed though? Because it's complaining that its supposed output files are missing.

**Comment by SolarAquarion** [comment]
it worked without npm run build before, i added npm run build and it now compiles
