### ISSUE TITLE
BUG: Tabby Does not start up on RHEL 7

### ISSUE THREAD

**Issue by Andy4Worc** [Eugeny/terminus#6805]
Hey, Tabby looks fun, but it doesn't seem to be working for me.
I've tried the latest two releases with `tabby-1.0.181-linux-x64.rpm` or the one before it and doing an rpm install ...
I've also tried doing a `yum install tabby-terminal`

Both lead to the same error if I were to try "tabby" to open it:
```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js:33:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}

```

I've ensured downloading latest versions of node and npm and general development tools ... I also tried restarting electron but that failed. Any ideas?

**Comment by Andy4Worc** [comment]
Hello?

**Comment by bensilea** [comment]
I also encountered this problem on RHEL 7.9
```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js:33:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}
[9550:0726/134650.290973:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[9583:0726/134650.334744:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[9583:0726/134650.338837:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

**Comment by bensilea** [comment]
`yum install tabby-1.0.189-linux-x64.rpm`

and run with  

`tabby --no-sandbox`
