### ISSUE TITLE
Cannot find module 'npm' under Win10

### ISSUE THREAD

**Issue by sburkett** [Eugeny/terminus#714]
I am getting the `Error: Cannot find module 'npm' message` on Win10 when trying to install a plugin. I can see the list of available plugins, but can't install any of them.

Things I've tried:

- Installed the latest nightly Win build (1.0.72)
- Confirmed that npm is in my %PATH%
- Typing `npm` commands in a `cmd` window work just fine.
- Added `npm: 'C:\Program Files\nodejs\npm'` to my Terminus config file

No matter what I try, I still get the error when trying to install a plugin. Any ideas? 

Thanks!

**Comment by sburkett** [comment]
This was in the debug log:

```
ERROR Error: Uncaught (in promise): Error: Cannot find module 'npm'
Error: Cannot find module 'npm'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at Module.nodeRequire.require (file:///C:/Users/Sburkett/AppData/Local/terminus/app-1.0.72/resources/app.asar/dist/bundle.js:3820:28)
    at require (internal/modules/cjs/helpers.js:20:18)
    at npmReady.resolve (C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\builtin-plugins\terminus-plugin-manager\dist\index.js:847:44)
    at new ZoneAwarePromise (C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\app.asar\node_modules\zone.js\dist\zone.js:891:29)
    at PluginManagerService.<anonymous> (C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\builtin-plugins\terminus-plugin-manager\dist\index.js:846:37)
    at Generator.next (<anonymous>)
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at Module.nodeRequire.require (file:///C:/Users/Sburkett/AppData/Local/terminus/app-1.0.72/resources/app.asar/dist/bundle.js:3820:28)
    at require (internal/modules/cjs/helpers.js:20:18)
    at npmReady.resolve (C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\builtin-plugins\terminus-plugin-manager\dist\index.js:847:44)
    at new ZoneAwarePromise (C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\app.asar\node_modules\zone.js\dist\zone.js:891:29)
    at PluginManagerService.<anonymous> (C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\builtin-plugins\terminus-plugin-manager\dist\index.js:846:37)
    at Generator.next (<anonymous>)
    at resolvePromise (C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\app.asar\node_modules\zone.js\dist\zone.js:814:31)
    at C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\app.asar\node_modules\zone.js\dist\zone.js:724:17
    at rejected (C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\builtin-plugins\terminus-plugin-manager\dist\index.js:603:89)
    at ZoneDelegate.invoke (C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\app.asar\node_modules\zone.js\dist\zone.js:388:26)
    at Object.onInvoke (C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17343:37)
    at ZoneDelegate.invoke (C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\app.asar\node_modules\zone.js\dist\zone.js:387:32)
    at Zone.run (C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\app.asar\node_modules\zone.js\dist\zone.js:138:43)
    at C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\app.asar\node_modules\zone.js\dist\zone.js:872:34
    at ZoneDelegate.invokeTask (C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\app.asar\node_modules\zone.js\dist\zone.js:421:31)
    at Object.onInvokeTask (C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334:37)
defaultErrorLogger @ C:\Users\Sburkett\AppData\Local\terminus\app-1.0.72\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768
```

**Comment by Adrian-Grimm** [comment]
Same with MacOS

**Comment by eliasjohansson** [comment]
I'm also getting this error when trying to install plugins. (MacOS)

**Comment by Hydragyrum** [comment]
Same error with Windows 7 and Terminus 1.0.72

**Comment by felipesnt** [comment]
Still having this problem on v1.0.79
