### ISSUE TITLE
Unable to connect to a reMarkable 2 via SSH

### ISSUE THREAD

**Issue by Gaibhne** [Eugeny/terminus#7501]
**Describe the problem**:
Attempting to connect to a reMarkable 2 tablet via SSH, which exposes itself as a USB networking device listening on `10.11.99.1`, Tabby just sits there:

```
 SSH  Connecting to 10.11.99.1
□ Connecting
```

No error is shown or produced. Any other SSH client I tried (OpenSSH, Windows built-in SSH, Kitty, Putty) connects just fine.

**Steps to reproduce the behavior**
Attempt to connect to a reMarkable 2, which I understand is not easy if you don't actually have one. I'll happily provide debug logs or whatever may be helpful.

**Details**
Version: 1.0.186
Platform: Windows x64 10.0.19045
Plugins: docker
Frontend: xterm-webgl

**Debug log output when attempting to connect**
`match found without corresponding matchIndex`

Coming every other second or so.

After I stop the attempted connection, I get an infinite spam of ever repeating errors like the following, which can only be stopped by shutting down Tabby completely:

```
Unhandled Promise rejection: Frontend not ready ; Zone: <root> ; Task: setInterval ; Value: Error: Frontend not ready
    at SSHTabComponent.<anonymous> (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:14727:23)
    at Generator.next (<anonymous>)
    at C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11128:71
    at new ZoneAwarePromise (zone.js:1427:1)
    at __awaiter (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11124:12)
    at SSHTabComponent.writeRaw (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:14725:16)
    at Object.write (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:14439:30)
    at Object.clearLine (node:internal/readline/callbacks:107:17)
    at Spinner.clearLine (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:5878:12)
    at Spinner.defaultOnTick [as onTick] (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:5781:8)
    at iteration (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:5828:10)
    at timer (zone.js:2378:1)
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Zone.runTask (zone.js:178:1)
    at invokeTask (zone.js:487:1)
    at ZoneTask.invoke (zone.js:476:1)
    at data.args.<computed> (zone.js:2358:1)
    at sentryWrapped (helpers.js:72:1) Error: Frontend not ready
    at SSHTabComponent.<anonymous> (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:14727:23)
    at Generator.next (<anonymous>)
    at C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11128:71
    at new ZoneAwarePromise (file:///C:/Users/me/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:126998:29)
    at __awaiter (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:11124:12)
    at SSHTabComponent.writeRaw (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:14725:16)
    at Object.write (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:14439:30)
    at Object.clearLine (node:internal/readline/callbacks:107:17)
    at Spinner.clearLine (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:5878:12)
    at Spinner.defaultOnTick [as onTick] (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:5781:8)
    at iteration (C:\Users\me\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-terminal\dist\index.js:5828:10)
    at timer (file:///C:/Users/me/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:127949:41)
    at _ZoneDelegate.invokeTask (file:///C:/Users/me/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:125977:31)
    at Zone.runTask (file:///C:/Users/me/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:125749:47)
    at invokeTask (file:///C:/Users/me/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:126058:34)
    at ZoneTask.invoke (file:///C:/Users/me/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:126047:48)
    at data.args.<computed> (file:///C:/Users/me/AppData/Local/Programs/Tabby/resources/app.asar/dist/bundle.js:127929:32)
    at sentryWrapped (C:\Users\me\AppData\Local\Programs\Tabby\resources\app.asar\dist\sentry.js:3891:23)
```

**Comment by Gaibhne** [comment]
This still exists, making it impossible for me to replace PuTTY with Tabby :(

The stacktrace no longer occurrs, but the `match found without corresponding matchIndex` error method still ticks once a second while Tabby is endlessly stuck in `Connecting` as described above.
