### ISSUE TITLE
Add connection: SSH

### ISSUE THREAD

**Issue by ronnieflip** [Eugeny/terminus#827]
Am having a hard time adding a connection under the ssh tab on windows. Any help?

**Comment by theatoken** [comment]
Meet this issuse too,
I found some errors in dev tool

`ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'isSupported' of undefined
TypeError: Cannot read property 'isSupported' of undefined
    at eval (webpack-internal:///17:56:43)
    at new ZoneAwarePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:891:29)
    at PasswordStorageService.loadPassword (webpack-internal:///17:55:16)
    at EditConnectionModalComponent.eval (webpack-internal:///16:55:67)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///16:16:71)
    at new ZoneAwarePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:891:29)
    at __awaiter (webpack-internal:///16:12:12)
    at EditConnectionModalComponent.ngOnInit (webpack-internal:///16:54:16)
    at checkAndUpdateDirectiveInline (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:22119:23)
    at resolvePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:814:31)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:724:17
    at rejected (webpack-internal:///16:14:89)
    at ZoneDelegate.invoke (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:388:26)
    at Object.onInvoke (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17343:37)
    at ZoneDelegate.invoke (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:387:32)
    at Zone.run (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:138:43)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:872:34
    at ZoneDelegate.invokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:421:31)
    at Object.onInvokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334:37)
defaultErrorLogger @ C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768
C:\Program Files\Terminus\resources\electron.asar\renderer\callbacks-registry.js:47 Uncaught (in promise) Error: Cannot find channel file "latest.yml", existing files:
{
  "name": "terminus-1.0.0-alpha.1-setup.exe.blockmap",
  "path": "terminus-1.0.0-alpha.1-setup.exe.blockmap",
  "repo": "generic",
  "package": "terminus",
  "version": "1.0.0-alpha.1",
  "owner": "eugeny",
  "created": "2019-05-19T18:17:13.785Z",
  "size": 107811,
  "sha1": "9aa2959ca2dbdd6740fb6366f173d9ea5e25222c",
  "sha256": "da567e841295d1c00e3e15c255b97fdbea93c52bf819aca0504f1a69ec02112a"
}
    at newError (C:\Program Files\Terminus\resources\app.asar\node_modules\builder-util-runtime\src\index.ts:29:17)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\electron-updater\src\providers\BintrayProvider.ts:31:15
From previous event:
    at BintrayProvider.getLatestVersion (C:\Program Files\Terminus\resources\app.asar\node_modules\electron-updater\src\providers\BintrayProvider.ts:23:25)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:347:26
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:443:21)
From previous event:
    at NsisUpdater.getUpdateInfoAndProvider (C:\Program Files\Terminus\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:336:43)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Program Files\Terminus\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:360:34)
    at NsisUpdater.checkForUpdates (C:\Program Files\Terminus\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:220:35)
    at callFunction (C:\Program Files\Terminus\resources\electron.asar\browser\rpc-server.js:252:24)
    at C:\Program Files\Terminus\resources\electron.asar\browser\rpc-server.js:411:10
    at EventEmitter.<anonymous> (C:\Program Files\Terminus\resources\electron.asar\browser\rpc-server.js:275:21)
    at EventEmitter.emit (events.js:194:13)
    at WebContents.<anonymous> (C:\Program Files\Terminus\resources\electron.asar\browser\api\web-contents.js:418:21)
    at WebContents.emit (events.js:194:13)
C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768 ERROR Error: Uncaught (in promise): [object Undefined]
    at resolvePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:814:31)
    at resolvePromise (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:771:17)
    at C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:873:17
    at ZoneDelegate.invokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:421:31)
    at Object.onInvokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334:37)
    at ZoneDelegate.invokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:420:36)
    at Zone.runTask (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:188:47)
    at drainMicroTaskQueue (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:595:35)
    at ZoneTask.invokeTask [as invoke] (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:500:21)
    at invokeTask (C:\Program Files\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:1540:14)`
