### ISSUE TITLE
Cannot find module '../build/Debug/pty.node' at launch on Ubuntu 18.04

### ISSUE THREAD

**Issue by JooDye** [Eugeny/terminus#8476]
```shell
> tabby 
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js
- /opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js
- /opt/Tabby/resources/app.asar/dist/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:2:109751)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js:33:15)
    at Module._compile (/opt/Tabby/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/unixTerminal.js',
    '/opt/Tabby/resources/app.asar/node_modules/@tabby-gang/node-pty/lib/index.js',
    '/opt/Tabby/resources/app.asar/dist/main.js',
    undefined
  ]
}
```

# Environment 
```
OS: Ubuntu 18.04 bionic
Kernel: x86_64 Linux 4.19.17
Uptime: 6h 4m
Packages: 3013
Shell: bash 4.4.20
Resolution: 2560x1440
DE: GNOME 
WM: GNOME Shell
WM Theme: 
GTK Theme: McOS-MJV-Dark-Gn-3.30-v2.0 [GTK2/3]
Icon Theme: Zafiro-icons-0.8.4
Font: Cantarell 11
CPU: Intel Core i7-8565U @ 8x 4.6GHz [47.0°C]
GPU: Mesa DRI Intel(R) UHD Graphics 620 (WHL GT2)
RAM: 8943MiB / 15852MiB
```

installed with [version 1.0.197](https://github.com/Eugeny/tabby/releases/download/v1.0.197/tabby-1.0.197-linux-x64.deb )

**Comment by bluecircle812** [comment]
>```shell ...

@Jasdent  how to solve

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ctxqlxs** [comment]
any update?
